ndk-build/src/cargo.rs
ndk-build/src/ndk.rs

Cross-compiling with build.rs using cc::Build and .use_cpp(true) (for
example) invokes <triple>-clang++ which is usually not on PATH or known
to point to the correct NDK. Set the CXX env var for the requested
triple to ensure the right C++ compiler is available and used.
---
Path logic remains in `fn clang`to do the same `exists()` check there. Let me know if this way of formatting and changing the name is the right way around.

ndk-build: Point CXX_<triple> to <triple>-clang++ from the ndk

---

ndk-build/src/apk.rs
ndk-build/src/config.rs
ndk-build/src/manifest.rs

use case: `<meta-data android:name="com.samsung.android.vr.application.mode" android:value="vr_only"/>`
naming of application_metadatas is rather unfortunate, suggestions?

support <meta-data> tags in manifest

---

ndk-sys/Cargo.toml
ndk-sys/src/lib.rs
ndk/Cargo.toml
ndk/src/bitmap.rs
ndk/src/hardware_buffer.rs
ndk/src/lib.rs

Continues the work for #22 
* adds Android Bitmap module. There are some additions to the NDK Bitmap in API-level-30, but I don't think it makes sense to add all of it before the full release, as things might still change.
* adds HardwareBuffer implementation. I'm not sure all the fence stuff is right, as I have no idea how to test it yet. I'll dive deeper when adding the camera API, that would also be the perfect time to add an example app using all of these modules.

Add bitmap and hardware buffer

---

ndk-sys/Cargo.toml
ndk-sys/src/lib.rs
ndk/Cargo.toml
ndk/src/aaudio.rs
ndk/src/bitmap.rs
ndk/src/hardware_buffer.rs
ndk/src/lib.rs
ndk/src/media/image_reader.rs

Adds bindings for Android NDK's AAudio interface (part of #22).
Also fixes an issue with previous PR where `*mut JNIEnv` pointers were getting dereferenced which doesn't as I expected.

Add AAudio interface

---

ndk-build/src/ndk.rs

Fix for https://github.com/rust-windowing/android-ndk-rs/issues/29
Toolchain binaries in the NDK are not wrapped by scripts and are thus normal executables with `.exe` extension. Only clang has (bash and batch) wrapper scripts, with none and with `.cmd` extension respectively.
I accidentally appended `++` after the filename in https://github.com/rust-windowing/android-ndk-rs/commit/33c00289ecc0a8ba54824c5c71b6a63233163c15 which should have gone inbetween the executable name and the (optional) extension. With this fix the path is properly `...-clang.cmd` and `...-clang++.cmd`

[ndk-build] Fix paths to toolchain and clang on Windows

---

cargo-apk/Cargo.toml
cargo-apk/src/apk.rs
ndk-build/Cargo.toml
ndk-build/src/ndk.rs
ndk-build/src/readelf.rs

Fix for https://github.com/rust-windowing/android-ndk-rs/issues/29
`SubCommand::target_dir()` seems to return an `std::fs::canonicalize`d path which is also called explicitly in `ndk-build`: this function utilizes [a Win32 function](https://doc.rust-lang.org/std/fs/fn.canonicalize.html#platform-specific-behavior) that returns UNC canonicalized paths with a special prefix that is not understood by many tools, including `cmd.exe`. 
Luckily the `dunce` crate has already solved all this trouble for us, and utilizes `std::fs::canonicalize` on platforms where this problem doesn't exist.

[cargo-apk/ndk-build] Use dunce to get rid of UNC paths on Windows

---

ndk-build/src/ndk.rs

NDK 20.1 - the latest NDK available through sdkmanager (...?) - has no
machine specifier on the architecture folder, at least on Windows. Try a
a folder without this postfix before bailing.
---
Didn't manage to download a bunch of NDKs (different architectures and versions) to validate what other platforms do, let's assume this applies there too. Otherwise users submit their issues/PRs in due time 😉

ndk-build: Fall back if no machine specific llvm prebuilt is found

---

cargo-apk/src/apk.rs

My previous commit introduced a canonicalize() here because target_dir()
returns a UNC path that is not supported by most tools. Needing the ?
operator should have rang a bell: dunce::canonicalize() calls
fs::canonicalize() first before stripping the UNC path. It bails if the
path doesn't exist, which happens in a clean environment when ./target
doesn't exist yet.
Luckily dunce also has a simplified() function to strip the UNC part off
the path without canonicalizing first.
Fixes: e9a6ee1c7321335e5cbb6eb4e5e9045531fe43e2
---
Apologies for the breakage!

fixup: cargo-apk: Do not canonicalize target_dir(), only strip UNC

---

Cargo.toml
README.md
ndk-examples/examples/hello_world.rs
ndk-glue/Cargo.toml
ndk-glue/src/lib.rs
ndk-macro/Cargo.toml
ndk-macro/src/expand.rs
ndk-macro/src/expand/backtrace.rs
ndk-macro/src/expand/logger.rs
ndk-macro/src/lib.rs
ndk-macro/src/parse.rs
ndk-macro/src/parse/backtrace.rs
ndk-macro/src/parse/logger.rs

Because a more convenient way of metaprogramming in rust related to proc_macro, I tried to replace `ndk_glue` macro with attribute procedural macro (`main`) which applied directly to main function.
* Enabling backtraces using env-var isn't default behavior now and can be done using `backtrace` property.
* Added `logger` property which configures _android_logger_ before entering to
main function.

Added `ndk_glue::main` attribute macro

---

ndk-macro/src/expand.rs
ndk-macro/src/expand/backtrace.rs
ndk-macro/src/parse.rs
ndk-macro/src/parse/backtrace.rs

Added support for `backtrace(full)` in `ndk-glue::macro`

---

.github/workflows/rust.yml
cargo-apk/src/apk.rs
ndk-build/src/apk.rs
ndk-build/src/config.rs
ndk/src/asset.rs
ndk/src/native_activity.rs

The working directory is for the `aapt` packing command is set to the target directory while the assets directory path from the manifest is just forwarded. This results in the android tool to not find the directory.
Tested locally on Windows.

Specify assets directory via fully-qualified path

---

cargo-apk/Cargo.toml
cargo-apk/src/apk.rs
cargo-apk/src/error.rs
cargo-apk/src/main.rs
ndk-build/Cargo.toml
ndk-build/src/config.rs
ndk-build/src/error.rs
ndk-build/src/ndk.rs
ndk-build/src/readelf.rs
ndk-glue/src/lib.rs
ndk/src/aaudio.rs
ndk/src/input_queue.rs
ndk/src/looper.rs
ndk/src/media/error.rs
ndk/src/media/image_reader.rs

fixes #16
before (cargo tree --invert failure):
```
failure v0.1.8
├── exitfailure v0.5.1
│   └── cargo-apk v0.5.1 (/home/jadsu/git/android-ndk-rs/cargo-apk)
└── which v3.1.1
└── ndk-build v0.1.1 (/home/jadsu/git/android-ndk-rs/ndk-build)
└── cargo-apk v0.5.1 (/home/jadsu/git/android-ndk-rs/cargo-apk)
```
after:
`error: package ID specification 'failure' matched no packages`
* Replaced some Error/Display impls with `thiserror`
* Fixed small clippy nits, remaining issues are now mainly missing native function safety docs.

Drop failure for anyhow, derive Error impls using thiserror

---

ndk-glue/Cargo.toml
ndk-glue/src/lib.rs

Since we generate these bindings in ndk-sys anyhow, there's no need for this crate. That's one less dependency when the "logger" feature is not used.

Remove android_log-sys dependency

---

cargo-apk/README.md
ndk-build/src/apk.rs
ndk-build/src/config.rs
ndk-build/src/manifest.rs

Allows changing the orientation of the screen by setting `android:screenOrientation` in the manifest. It might be worth adding to the cargo-apk readme that the default value of "unspecified" doesn't do any rotation for you at all, but "sensorLandscape" and "sensorPortrait" allow rotation from their normal orientations and their reverse orientations.

Add screenOrientation configuration via metadata

---

cargo-apk/README.md
cargo-apk/src/apk.rs
ndk-build/src/config.rs

Allows you to change the label of your APK using the metadata in your Cargo.toml. Hope this is useful!

Allow change apk label with apk_label in metadata

---

.github/workflows/rust.yml

`rustfmt` is not included always in the nightly releases, resulting in spurious ci build fails

ci: only format on stable channel

---

.github/workflows/publish.yml
ndk-glue/Cargo.toml
ndk-sys/Cargo.toml
ndk/Cargo.toml

Replacement for https://github.com/rust-windowing/android-ndk-rs/pull/14
Automatically publish crates once the versions get bumped on the master
Reverts the old 0.1.1 version bumps which got yanked due to breaking compatibility
I'm not 100% this works atm, but I guess the secrets are setup already

CI publishing workflow

---

cargo-apk/CHANGELOG.md
cargo-apk/Cargo.toml
ndk-build/CHANGELOG.md
ndk-build/Cargo.toml
ndk-glue/CHANGELOG.md
ndk-glue/Cargo.toml
ndk-macro/CHANGELOG.md
ndk-macro/Cargo.toml
ndk-sys/CHANGELOG.md
ndk-sys/Cargo.toml
ndk/CHANGELOG.md
ndk/Cargo.toml

Fixes #59
This bumps the minor version for `ndk`, `ndk-sys`, `ndk-glue`, and `ndk-macro`, and bumps the patch version for `cargo-apk` and `ndk-build`.
I've also changed all of the Cargo.toml `authors` fields to "The Rust Windowing contributors", keeping with the convention used in winit and gfx.

Bump versions

---

cargo-apk/CHANGELOG.md
cargo-apk/src/apk.rs

Currently, there's an error if you try to specify the `res` folder in the project that running not from root Cargo.toml

Fix res folder resolve

---

.github/workflows/rust.yml

curl download of the ndk seems to fail pretty frequently today at least causing the builds to fail most of the time.
This caches the ndk download which shoves off ~45sec from each build (which so far took 4-5min each)

ci: cache ndk download

---

cargo-apk/CHANGELOG.md
cargo-apk/Cargo.toml
ndk-glue/CHANGELOG.md
ndk-glue/Cargo.toml
ndk-sys/CHANGELOG.md
ndk-sys/Cargo.toml
ndk-sys/src/lib.rs
ndk/CHANGELOG.md
ndk/Cargo.toml

Only build for docs.rs targets and remove the `rustdoc` workaround
Fixes https://github.com/rust-windowing/android-ndk-rs/issues/80

Explicitly set docs.rs targets

---

cargo-apk/Cargo.toml

Resolves https://github.com/rust-windowing/android-ndk-rs/issues/74
Updated cargo-subcommand dependency which fixes glob workspaces.

Dependency fix for glob workspaces.

---

cargo-apk/CHANGELOG.md
cargo-apk/Cargo.toml

As requested by https://github.com/rust-windowing/android-ndk-rs/pull/85#issuecomment-719970447 for bevy

Bump cargo-apk version to 0.5.4

---

.github/workflows/rust.yml
ndk-glue/Cargo.toml
ndk/Cargo.toml

When using && to cd back out of a subdirectory the error code from cargo test is implicitly consumed instead of being caught by set -e.  While this does return a non-zero exit code it does not prevent the rest of the script from running if more lines follow.
The next lines run and, if successful, do not fail the step because GH actions base the result of a multiline shell script solely on the last command [1].
You can try this for yourself by throwing the following three steps in GH actions and observing the result [2]:
false
echo "This is not printed"
false && echo "This is not printed"
false && echo "This is not printed"
echo "Oh noes, his is printed, and the script exits successfully"
In addition structuring the tests this way allows working-directory to be used, and shows every test …

ci: Run all tests in isolation

---

.github/workflows/publish.yml

This prevents the Publish job from running on forks whenever someone pushes to master (ie. to update it to upstream).

ci: Only run publishing job when the repository_owner is rust-windowing

---

.github/workflows/rust.yml
ndk-build/src/ndk.rs

GitHub already includes the Android SDK/NDK and Java in their image, no need to download and install it again slowing down the build process.
Also run at least one build job on Windows to make sure it remains sane. It didn't seem necessary to run both nightly and stable for every target though.
Note that this is in part to bring to attention an issue with spaces in CC/LINKER paths:
```
error: linking with `C:\Program Files (x86)\Android\android-sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\aarch64-linux-android30-clang.cmd` failed: exit code: 1
|
= note: "C:\\Program Files (x86)\\Android\\android-sdk\\ndk-bundle\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\aarch64-linux-android30-clang.cmd" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-Wl,--allow-multiple-definition" …
```

ci: Remove obsolete NDK/Java setup and run once on Windows

---

ndk-build/src/dylibs.rs
ndk-build/src/ndk.rs

`$ndk/platforms` is deprecated and finally removed in r22; android-ndk-rs was never using this so it's safe to remove.
If NDK platform compatibility checking is still desired, we should check for `$ndk/toolchains/${toolchain:-llvm}/prebuilt/${host:-linux-x86_64}/sysroot/usr/lib/$triple/$api/` (Linux ndk, might differ on other platforms) instead.
At the same time perform some minor code cleanup. How are the maintainers feeling about enabling `clippy` in the CI and fixing few remaining issues?

ndk-build: Support NDK r22

---

cargo-apk/CHANGELOG.md
cargo-apk/Cargo.toml
cargo-apk/README.md
ndk-build/CHANGELOG.md
ndk-build/Cargo.toml
ndk-build/src/apk.rs
ndk-build/src/config.rs
ndk-build/src/manifest.rs

Fixes #95 - although it would nice to introduce a proper serialize + deserialize mechanism for generating the `AndroidManifest.xml`
Would love to see this released in `cargo-apk` immediately after as it's a must feature for a project that I'm working on. Thanks in advance! :)

Added android:launchMode configurability

---

cargo-apk/CHANGELOG.md
cargo-apk/Cargo.toml
cargo-apk/src/apk.rs
ndk-build/CHANGELOG.md
ndk-build/Cargo.toml
ndk-build/src/apk.rs
ndk-build/src/config.rs

Small fix using `dunce::simplified` when extracting the manifest's assets and resource folder instead of only using it in  `aapt.arg(dunce::simplified(assets))`. Also bumped the versions as I would love to see this published. :)

Fixed UNC path handling on Windows for resource folder

---

ndk/src/aaudio.rs
ndk/src/event.rs

Fixes #97
Fixes a broken link to `pointer_id`, and removes a link to `set_callbacks` that doesn't exist (not here nor in history, any idea what it should have pointed to?).
It doesn't seem like internal links are used anywhere else in the documentation... Perhaps we should go in and add `[]` around all inline code blocks referring to some type/function to make that link official?
For other improvements, how about using [`#[doc(alias = "ANative...")]`](https://doc.rust-lang.org/rustdoc/advanced-features.html#add-aliases-for-an-item-in-documentation-search) on all safe wrapper functions to make them searchable by their native variant?

Fix broken links in docs

---

.github/workflows/rust.yml
ndk/Cargo.toml
ndk/src/aaudio.rs
ndk/src/media/image_reader.rs

Following the removal of `set_callback` in #107 this re-introduces the "proper" doc (according to NDK docs) to `AudioStreamDataCallback`. At the same time the rest of the docs have been upgraded to use intra links (it is hard to resist: start cleaning up one line, but the rest can't be left behind; that'd be inconsistent).
Some names were broken or renamed in Rust, again signifying the relevance of proper doc links. Not only is it useful for readers to click through to a reference, it also ensures that reference is valid at build time making sure the documentation is useful at all times (yeah - you always end up grepping for that one function in the docs, frustrated that it doesn't seem to exist anywhere).
More importantly this adds missing features for API level 25, 27 and 28. 28 is used …

ndk: Add missing API levels, use intra-links in AAudio docs

---

ndk/src/aaudio.rs

Fixes https://github.com/rust-windowing/android-ndk-rs/pull/108#discussion_r554393678
Autolinks escape `[]` resulting in `AudioTrack#write(float%5B%5D,%20int,%20int,%20int)` which is not resolved to the right anchor on android.com. Using `<a>` however does not apply escaping rules, allowing the link to work properly.

ndk/aaudio: Fix link to AudioTrack#write

---

.github/workflows/rust.yml

An obscure one-line `apk build` failure got shadowed by a much larger deprecation warning shown by `cargo check` right above, deemed irrelevant. Separating these steps will make it clear when the issue is code-related (ndk, ndk-glue) or build-related (ndk-build, cargo-apk, cargo-subcommand).
---
GH actions virtual environments have finally been fixed to provide a space-less path to the SDK and NDK by default :tada:. The workaround - introduced in #92 - can finally be removed again!

Remove Windows NDK symlink and run apk check + build in separate steps

---

ndk-glue/CHANGELOG.md
ndk-glue/Cargo.toml
ndk-glue/src/lib.rs
ndk/CHANGELOG.md
ndk/Cargo.toml
ndk/src/input_queue.rs

The value of `0` or `1` is not a valid pointer to a userdata structure.  Not that it has to be, but with the nasty consequence that winit Android code was accidentally reinterpreting this pointer as integer to extract the identifier from, instead of using the appropriate `ident` field directly. After that is addressed in winit we can set the pointer back to 0 cleanly (and prepare for a potential pointer to some user data that may be passed in the future).
Also add some constants to document these "special" identifiers.
---
Maintainers, this is a breaking change in `ndk-glue` that we want to bump our minor version for, to v0.3. Anyone upgrading now will always see `null()` in the `data` field, wrecking `winit` unless https://github.com/rust-windowing/winit/pull/1826 is in, which will only …

ndk,ndk-glue: Do not pass Looper ident as userdata pointer

---

.github/workflows/rust.yml

Following https://github.com/rust-windowing/android-ndk-rs/pull/106#pullrequestreview-565655645
Only `ndk` docs are built for all `android` targets but the rest of the documentation remains untested. Especially now that we're expanding to provide more complete docs for ndk-build and cargo-apk should everything be tested, to make sure that things like intra-doc links remain in working order.
The `ndk` docs build successfully here thanks to the `test` feature (enabled by `--all-features`); does it still make a lot of sense to build-test the documentation for every target individually?

ci: Check all crate documentation in addition to target-specific ndk

---

.github/workflows/rust.yml

From https://github.com/rust-windowing/android-ndk-rs/pull/129#issuecomment-803299047
A lot of these steps - except apk building - are not target-specific (do not have a `--target` option; `target:` on `actions-rs/toolchain` only specifies what targets to install). This is a waste of time despite all duplication running in parallel, and could be used to run a target-specific apk build in parallel with host-side tests instead.
It should be fine to perform just the apk build step on Windows, and leave the rest (tests, documentation) to Linux runners only - most of those steps were not ran on Windows anyway.
This takes CI time down from 6m30s to just under 5m, with around 3m spent in apk building (in parallel), 3m40s spent testing all cates and docs on the host, and under 5m for apk building …

ci: Run target-agnostic build/test steps only once 

---

ndk-glue/src/lib.rs
ndk/src/looper.rs

Android only performs additional initialization like providing an input queue through `onInputQueueCreated` after the main initialization function (`ANativeActivity_onCreate`) returns.  In some cases it is possible that the main thread spawned here hasn't attached a looper to its thread and assigned it to the accompanying `LOOPER` static variable yet, resulting in a `None` unwrap when Android provides us with an input queue.
This race condition is simply solved by not returning from `fn init()` (`ANativeActivity_onCreate`) until the thread has finished its setup, through wrapping `LOOPER` in a `Mutex` and using a condition variable to signal when it is ready.
This condition is intentionally not exposed to `on_input_queue_created` may we ever have a cleanup procedure that sets `LOOPER` …

ndk-glue: Don't return from onCreate until LOOPER is created

---

ndk-glue/src/lib.rs

Currently, some `NativeActivity` callbacks (`on_native_window_destroyed`, `on_input_queue_destroyed`):
(1) acquire a write lock on a static handle to the resource that is about to be destroyed, (2) drop the handle, (3) dispatch an asynchronous `Event` to the user on a UNIX pipe notifying of the release, (4) immediately return from the callback.
This is incorrect according to [`ANativeActivityCallbacks docs`](https://developer.android.com/ndk/reference/struct/a-native-activity-callbacks#struct_a_native_activity_callbacks_1a6aaafbbfae4c0ac066b9d61ebb3ab97f). If the user is holding on to a read lock on the handle (as they should), there will be a deadlock. If the user does not have a read lock on the handle, there is a race condition, since Android may free the resource before the user …

Notify event pipe before releasing NativeActivity resources

---

ndk-build/src/error.rs
ndk-build/src/ndk.rs

Since [r21] LLVM binutils are included _for testing_;
Since [r22] GNU binutils are deprecated in favour of LLVM's;
Since [r23] GNU binutils have been removed.
When GNU binutils are not available (`<triple>-<bin_name>`) "fall back" to `llvm-<bin_name>` binaries from LLVM binutils that are now included with the NDK.
To maintain stability with the current ndk-build crate release, prefer GNU binutils for as long as it is provided by the NDK instead of trying to use `llvm-<bin_name>` from r21 onwards.
[r21]: https://github.com/android/ndk/wiki/Changelog-r21
[r22]: https://github.com/android/ndk/wiki/Changelog-r22
[r23]: https://github.com/android/ndk/wiki/Changelog-r23
Fixes #135
---
We could also opt for LLVM binutils in r22 (requires extra logic to figure out whether we're building on r21 or …

ndk-build: Use LLVM binutils when GNU binutils are removed (r23+)

---

cargo-apk/CHANGELOG.md
cargo-apk/README.md
cargo-apk/src/apk.rs
cargo-apk/src/manifest.rs
ndk-build/CHANGELOG.md
ndk-build/src/apk.rs
ndk-build/src/manifest.rs

Fixes #145
Application label was used for apk file naming. Unfortunately, it lacks use of string resource id in application label. Application name (i.e. `applicaiton:name` tag in `AndroidManifest.xml`) is more appropriate for apk naming.

Add support for android string resource id in application label. (#145)

---

cargo-apk/src/main.rs

Cargo supports the `c`/`b`/`r` (and `t` for `test`) short-hands to quickly execute often-used commands.  I keep reaching for these and forgetting cargo-apk doesn't support those, when we easily can.

cargo-apk: Add c/b/r shorthand for check/build/run like cargo

---

ndk/src/looper.rs

No entry in the changelog, this improvement isn't worth mentioning.

ndk/looper: Use intra-doc links

---

ndk-glue/CHANGELOG.md
ndk-glue/src/lib.rs
ndk/CHANGELOG.md
ndk/Cargo.toml
ndk/src/looper.rs

The `event` field/parameter cannot have more states than these few carefully defined constants, and should be exposed as a proper restricted type since it's part of the public API.

looper: Model `ALOOPER_EVENT` with `bitflags`

---

README.md

Not sure if we want this as high up on the `README` though, but it should be helpful for us to keep track and for crate users to know what to expect (ie. that r23 isn't going to work until a newer Rust release that doesn't depend on `libgcc` anymore).

README: Document tested and supported NDK versions

---

ndk-macro/Cargo.toml
ndk-macro/src/helper.rs

Depends on #162 
proc-macro-crate 1.0 released, and [num_enum] bumped to that recently in a patch release causing a duplicate dependency in `Cargo.lock`.  We can upgrade to it too.
[num_enum]: https://github.com/illicitonion/num_enum/commit/8385dc995b6a796b02e072f02e9019f15b334791

ndk-macro: Update proc-macro-crate to 1.0, update darling to 0.13

---

ndk-glue/CHANGELOG.md
ndk-glue/Cargo.toml

Fixes #164 
It seems these threading fixes went unnoticed for a while as they didn't have anything added to `CHANGELOG.md`. Still, they're both vital in preventing deadlocks and race-conditions.
I don't think any of these are breaking and warrant a minor release, so a patch should be fine to get it in everyones hands smoothly, before the next breaking changes (see open PRs) land.

ndk-glue: Add missing entries to changelog and perform patch release 0.3.1

---

ndk-build/CHANGELOG.md
ndk-build/Cargo.toml
ndk-glue/CHANGELOG.md
ndk-glue/Cargo.toml
ndk/CHANGELOG.md
ndk/Cargo.toml

Fixes #164
~ndk-glue 0.3.1 depends on a breaking change in the NDK, and can only be released if that's released under 0.4.0.~
---
~Draft: I'm not sure if this is the right thing to do, or if we should aim for ndk-glue `0.4.0`. ndk-glue exposes quite a few NDK symbols in its public API, and running `cargo update` in a crate that uses both (very likely) they'll end up with duplicate crates and incompatible types unless they manually update to ndk 0.4 (which is possibly, but unexpected sudden breakage because semver allows going from 0.3.0 to 0.3.1 without issues).~
---
ndk-glue depends on a breaking change in the NDK, and can only be released if that's released under 0.4.0.  This, in turn, causes ndk-glue to need a minor bump too despite no other breaking changes, as NDK symbols are used in …

Release ndk 0.4.0, ndk-glue 0.4.0, ndk-build 0.4.1

---

cargo-apk/CHANGELOG.md
cargo-apk/Cargo.toml
ndk-build/CHANGELOG.md
ndk-build/Cargo.toml
ndk-build/src/apk.rs

On Windows, using a backslash path for the library results in a runtime error where it fails to load the .so file.
```
prev: "lib/arm64-v8a/libhello_world.so"
new: "lib\\arm64-v8a\\libhello_world.so"
```

ndk-build: fix native activity library path on non-UNIX systems

---

ndk-glue/src/lib.rs
ndk/src/aaudio.rs
ndk/src/asset.rs
ndk/src/configuration.rs
ndk/src/event.rs
ndk/src/input_queue.rs
ndk/src/looper.rs
ndk/src/native_activity.rs
ndk/src/native_window.rs

Filing this as a separate PR in preparation for `clippy` linting in the CI, just so that these nontrivial documentation changes can be reviewed properly.

Add missing safety docs

---

ndk/src/looper.rs

The box created in `add_fd_with_callback` is turned into a raw pointer but its memory is never dropped when the callback requests for deregistration.
Note that it is still possible to deregister this callback using `ALooper_removeFd`, where the box cannot be accessed and would thus leak.  This is likely not a problem in practice because that function is not exposed in the safe API at the time of writing.
However, it is still possible to replace the callback by calling `ALooper_addFd` on the same `fd` again, leaking the boxes.
---
As an alternative we can write this in a (probably?) cleaner way by always converting back to a `Box` and instead preventing it from being dropped:
```rust
let mut cb = Box::<Box<dyn FnMut(RawFd) -> bool>>::from_raw(data as *mut _);
let keep_registered = cb(fd); …
```

ndk/looper: Drop boxed callback after deregistering

---

ndk-glue/CHANGELOG.md
ndk-glue/src/lib.rs

This completes #134 by applying the same pointer-equality check in `on_input_queue_destroyed` to `on_window_destroyed`, and documents when the user should hold on to or release any of the `RWLock`s to ensure proper lifetimes for dependencies like surfaces in graphics APIs.

ndk-glue: Document lock behaviour in `Event` and ensure pointer equality

---

cargo-apk/CHANGELOG.md
cargo-apk/src/apk.rs

When specifying multiple build targets (e.g --examples) only the first artifact was used to derive the library name.
In the `AndroidManifest.xml` the key `android:name="android.app.lib_name"` would always have the same value for each artifact. The resulting application wouldn't be able to correctly load the library on runtime.
This surfaced in the CI changes https://github.com/rust-windowing/android-ndk-rs/pull/169 which builds all examples with a single command. The uploaded apk artifacts may not run correctly as they internally refer to the jni-audio library.

cargo-apk: Fixed the library name in case of multiple build artifacts 

---

ndk/CHANGELOG.md
ndk/src/looper.rs

According to [the documentation]: `The identifier must be >= 0, or ALOOPER_POLL_CALLBACK if providing a non-NULL callback.` This makes sense because the identifier is not returned anywhere when the callback fires.
[the documentation]: https://developer.android.com/ndk/reference/group/looper#alooper_removefd

ndk/looper: Pass ALOOPER_POLL_CALLBACK ident when adding fd callback

---

ndk/CHANGELOG.md
ndk/src/looper.rs

For https://github.com/rust-windowing/android-ndk-rs/pull/172#discussion_r684681058
b0f2148 ("ndk/looper: Drop boxed callback after deregistering (#172)") improved `add_fd_with_callback` to use a generic type instead of `dyn FnMut`, allowing us to get rid of a double `Box` that would otherwise be needed to hold the fat pointer with vtable.  Since the API is changing for the next `ndk` release anyway (`ident` has been removed as this has to use the `ALOOPER_POLL_CALLBACK` constant) we can also remove the `Box` implementation detail.  A new `Box` is still created just like the previous implementation though, since the lifetime of the closure is now unknown (at least as long as Android might be calling it).

ndk/looper: Accept unboxed closure in add_fd_with_callback

---

ndk-examples/Cargo.toml
ndk-examples/examples/looper.rs

Fixes #111
Originally proposed [here], this adds a simple looper example demonstrating how to use Android's `Looper` through the NDK bindings in similar fashion to `winit`.  It uses `ndk_glue`'s event pipe, Android's `InputQueue` and a custom Unix pipe to transfer events to the Looper (thread).
[here]: https://github.com/rust-windowing/android-ndk-rs/issues/111#issuecomment-768118616

ndk-example: Demonstrate Looper usage without winit

---

ndk/CHANGELOG.md
ndk/src/aaudio.rs
ndk/src/configuration.rs

- ndk/aaudio: Replace "Added in" comments with missing `#[cfg(feature)]`
- ndk/aaudio: Add missing `fn get_allowed_capture_policy()`
- ndk/configuration: Add missing `api-level-30` to `screen_round()`

ndk: Add missing `feature="api-level-XX"` guards

---

README.md
cargo-apk/CHANGELOG.md
cargo-apk/src/apk.rs
ndk-build/CHANGELOG.md
ndk-build/src/ndk.rs

Fixes #149
Rust still searches for libgcc even though [85806] replaces internal use with libunwind, especially now that the Android NDK (since r23-beta3) doesn't ship with any of gcc anymore.  The apparent solution is to build your application with nightly and compile std locally (`-Zbuild-std`), but that is not desired for the majority of users.  [7339] suggests to provide a local `libgcc.a` as linker script, which simply redirects linking to `libunwind` instead - and that has proven to work fine so far.
Intead of shipping this file with the crate or writing it to an existing link-search directory on the system, we write it to a new directory that can be easily passed or removed to `rustc`, say in the event that a user switches to an older NDK and builds without cleaning.  For this we …

cargo-apk: Work around missing libgcc on NDK r23 with linker script

---

.github/workflows/rust.yml

We only care about starting a very simple UI-less app for now, and this seems to fix the deadlock that occurs right about every CI emulator job just before `adb install` runs.  It hopefully also makes the runs a bit faster, but this wasn't measured/compared in detail due to already high runtime variance.

ci emulator: Disable animations and other UI/UX features

---

ndk-glue/CHANGELOG.md
ndk-glue/Cargo.toml
ndk-macro/CHANGELOG.md
ndk-macro/Cargo.toml
ndk-sys/CHANGELOG.md
ndk-sys/Cargo.toml
ndk/CHANGELOG.md
ndk/Cargo.toml

Bump versions for all crates providing Android-specific code.

Release ndk-sys-0.2.2, ndk-0.5.0, ndk-macro-0.3.0, ndk-glue-0.5.0

---

cargo-apk/CHANGELOG.md
cargo-apk/Cargo.toml
ndk-build/CHANGELOG.md
ndk-build/Cargo.toml
ndk-glue/CHANGELOG.md
ndk-macro/CHANGELOG.md
ndk-sys/CHANGELOG.md
ndk/CHANGELOG.md

Bump versions for the host tooling.

Release ndk-build-0.4.3, cargo-apk-0.8.2

---

.github/workflows/rust.yml

Our CI currently builds and runs the emulator three times, once for every possible APK source.  It is possible to speed up this setup by only building the image once as per [1] and storing it using GitHub's cache system.  This approach was suggested in https://github.com/rust-windowing/android-ndk-rs/pull/133#issuecomment-967221312.
[1]: https://github.com/ReactiveCircus/android-emulator-runner#usage
CC @Gordon-F for the suggestion!

ci emulator: Cache AVD emulator setup to speed up repeated jobs

---

cargo-apk/CHANGELOG.md
cargo-apk/src/apk.rs

Fixes #193, cc @hrydgard 
According to [1] minSdkVersion is used to determine the compiler target and ultimately limit what API is available at compile-time.  This is most likely because using/linking newer API will result in runtime linker errors on these older platforms.
[1]: https://developer.android.com/ndk/guides/sdk-versions#minsdkversion
---
I think we still have a couple things to do here:
- Now that `min_sdk_version` is mandatory (see the unwrap), perhaps we should default it to the _minimum_ SDK level available in the NDK (the `min()` of `default_platform()`)?;
(obviously reword the defaults in the cargo-apk docs);
- Remove the "arbitrary" default of minimum version 23?  Does anyone recall why this was chosen?  NDK r24 beta still ships with support for SDK level 21, which would …

cargo-apk: Use `min_sdk_version` to select compiler target

---

cargo-apk/CHANGELOG.md
cargo-apk/README.md
cargo-apk/src/apk.rs
ndk-build/CHANGELOG.md
ndk-build/src/apk.rs
ndk-build/src/ndk.rs

Depends on #197
As discussed in [197] setting `target_sdk_version` to the "arbitrary" highest available SDK version is nonsense.  This target version (unlike `min_sdk_version` which defines the least set of symbols that should be available) has real impact on the runtime of an application, in particular the compatibility or stringency of rules Android applies to your application.  Certain APIs may not work at all or be heavily restricted on newer target versions because they are deemed too dangerous, and Android expects the user has tested their app against these limitations and is communicating this by setting `target_sdk_version` to that particular value.  Hence this shouldn't change purely based on the environment, even for the default.
To retain some backwards compatibility with …

ndk-build,cargo-apk: Default `target_sdk_version` to 30 or lower

---

ndk/CHANGELOG.md
ndk/src/hardware_buffer.rs

~I suppose this was a mistake because there is no other way of accessing the underlying pointer.~ It probably isn't a mistake since other structs also have `as_ptr()` private. But `HardwareBuffer` should be spacial and have `as_ptr()` public, I need the pointer to import the memory into Vulkan.

Make `HardwareBuffer::as_ptr()` public

---

ndk/CHANGELOG.md
ndk/src/configuration.rs

Just like `fn language()` the country can be unset in a configuration, resulting in a string with two null bytes being returned to the caller.  As the caller might not necessarily be aware of this detail, provide them with a more explicit representation of "unset" like `language()`.

ndk/configuration: Return `None` from `fn country()` when unset

---

.github/workflows/publish.yml
ndk-examples/Cargo.toml
ndk-examples/examples/jni_audio.rs
ndk-glue/CHANGELOG.md
ndk-glue/Cargo.toml
ndk-glue/src/lib.rs

In order to show that [#223] solves our problem ([#211]) with multiple ndk-glue versions in tree, all having their own `static` globals, backport the `ndk-context` initialization to `ndk-glue 0.5` so that everyone on `winit 0.26` (pending a `winit 0.27` release) can be compatible with other crates using the Java VM and/or Android Context.  These crates will need to migrate to `ndk-context` first though.
[#211]: https://github.com/rust-windowing/android-ndk-rs/issues/211
[#223]: https://github.com/rust-windowing/android-ndk-rs/pull/223

ndk-glue: Initialize ndk-context on 0.5 stable releases

---

.github/workflows/publish.yml
ndk-examples/Cargo.toml
ndk-examples/examples/jni_audio.rs
ndk-glue/CHANGELOG.md
ndk-glue/Cargo.toml
ndk-glue/src/lib.rs

In order to show that [#223] solves our problem ([#211]) with multiple ndk-glue versions in tree, all having their own `static` globals, backport the `ndk-context` initialization to `ndk-glue 0.4` so that everyone on this older crate can be compatible with other crates using the Java VM and/or Android Context.  These crates will need to migrate to `ndk-context` first though.
[#211]: https://github.com/rust-windowing/android-ndk-rs/issues/211
[#223]: https://github.com/rust-windowing/android-ndk-rs/pull/223

ndk-glue: Initialize ndk-context on 0.4 stable releases

---

.github/workflows/publish.yml

This crate is missing in the list and has previously been published manually.
---
@dvc94ch I noticed this by seeing a different publisher on the ndk-context and ndk-glue crates, note that we can do publishing straight from `master` and there's no need to do it locally :)

gh/publish: Publish ndk-context crate directly from CI

---

ndk-macro/src/helper.rs

`proc_macro_crate::crate_name` fails to find our `ndk-glue` crate when it sits inside `[target.'cfg(target_os = "android")'.dev-dependencies]` as shown in [RustAudio/cpal#641], with a fix pending in [bkchr/proc-macro-crate#15].  This function is only ever called with `"ndk-glue"` which is an invalid identifier and should have its dash replaced with an underscore to be valid.  However, since this fallback doesn't seem to have been hit before (we've never received reports of `` `"ndk-glue"` is not a valid identifier ``) it is safe and desired to enforce the crate name to reside in `Cargo.toml` and `proc-macro-crate` being able to find it.
[RustAudio/cpal#641]: https://github.com/RustAudio/cpal/runs/5203107529?check_suite_focus=true
[bkchr/proc-macro-crate#15]: …

ndk-macro: Remove faulty crate name fallback in `fn crate_path()`

---

cargo-apk/CHANGELOG.md
cargo-apk/README.md
cargo-apk/src/apk.rs

Allows specifying `package` under the `[package.metadata.android]` section of `Cargo.toml`. This removes an `assert` that `package` is empty and only uses the previous forced value of `rust.<crate_name>` if `package.metadata.android.package` is empty.
cc: @MarijnS95 
Closes #234

Allow specifying manifest `package` property in `Cargo.toml`

---

ndk-build/src/readelf.rs

Avoid AAPT errors stemming from attempts of adding the same library twice

---

ndk/CHANGELOG.md
ndk/src/media/media_codec.rs
ndk/src/media/mod.rs

Add `MediaCodec` and `MediaFormat` bindings with most of their methods. Crypto and DRM support is not implemented.
**Testing**
Only the decoder code path is tested. [sample](https://github.com/alvr-org/ALVR/blob/master/alvr/experiments/client/src/video_decoder/mediacodec.rs)
**Note:** This PR needs to be rebased after #213 is merged

Safe mediacodec bindings

---

.github/workflows/android_test.sh

Make sure the package is removed since it may end up in the AVD cache.  This causes `INSTALL_FAILED_UPDATE_INCOMPATIBLE` errors when the debug keystore is regenerated, as it is not stored/cached on the CI: https://github.com/rust-windowing/android-ndk-rs/blob/240389f1e281f582b84a8049e2afaa8677d901c2/ndk-build/src/ndk.rs#L308-L332
CC @Gordon-F, perhaps you have an idea why this started happening all of a sudden?

ci/android_test: Remove possibly-cached APK from AVD before installing

---

ndk-build/src/readelf.rs

A small bugfix to a bug introduced with #187, as `libc++_shared.so` is added into the `provided` hashset when crawling Android NDK search paths, which are assumed present on-device, but this particular case is neither on-device, nor ends up included as an artifact when bundling needed libraries.

Fix provided libs hashset containing those missing on-device

---

ndk/src/configuration.rs
ndk/src/lib.rs
ndk/src/media/media_codec.rs

`trivial-casts` is allowed by default as it still has some odd cases where the lint triggers incorrectly or is difficult to fix.  For our intents and purposes however it works just fine and prevents against riddling the code with unnecessary - usually untyped - `as` casts.
https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html#explanation-22
CC @zarik5, #216

ndk: Remove and warn on trivial casts

---

cargo-apk/CHANGELOG.md
cargo-apk/src/apk.rs
ndk-build/CHANGELOG.md
ndk-build/src/manifest.rs

The other two manual `serialize_with` functions have a very clear purpose of making the datastructure easier to work with, by turning a vector of strings into a more verbose XML element with the string as `name` field.
No such case with `intent_filter`, which needs no special serialization treatment but instead performs actual business logic to insert more elements based on what the caller wishes to serialize.  This sort of logic is better moved to `cargo-apk` where a toml-parsed manifest is similarly enriched with sensible defaults to make Android development as accessible and out-of-the-box as possible.
---
As discussed in #204, this seems to be the most sensible place (or should we get something that mimicks `serde(default)` so that it's present earlier on? - might be more tricky to …

ndk-build: Move default serialization of `MAIN` intent filter to `cargo-apk`

---

ndk/src/bitmap.rs
ndk/src/media/error.rs
ndk/src/media/image_reader.rs
ndk/src/media/media_codec.rs
ndk/src/media/mod.rs

By far the most calls of this function pass a closure that returns the void type.  All these default calls can be simplified by always returning the void type in `Result<()>` from `fn from_status()`, and use the standard `Resuld::map(|()| ...)` to provide a different ok-value in the few cases an actual return value is desired.

ndk: Remove on_success closure argument from `fn from_status()`

---

cargo-apk/CHANGELOG.md
cargo-apk/README.md
cargo-apk/src/apk.rs
ndk-build/CHANGELOG.md
ndk-build/src/manifest.rs

Depends on #241
Subsumes #204
Similar to how we help the user with a default `MAIN` intent filter to launch the sole `NativeActivity` in their application (and setting a few other sensible defaults), we should also set Android's new `android:exported` attribute to `true` if they're targeting Android S (SDK 31) or higher.
Without this set to `true` the Rust app is not allowed to be started externally (by ie. a launcher or `adb`) on Android S+, and with only a single `Activity` currently supported by `ndk-build` it is unlikely (but not impossible, see shared user IDs etc), that there are other means to start it internally.
https://developer.android.com/guide/topics/manifest/activity-element#exported

cargo-apk: Export native activity by default on Android S and up

---

cargo-apk/CHANGELOG.md
cargo-apk/src/main.rs

Print the package name and version from `Cargo.toml` that the crate/binary was built with.
Note that we still have to address [EDIT: don't use the word `fix` here to not trigger auto issue linking] #217 somehow to make this truly useful, without having to switch to a directory that contains a valid crate setup.

cargo-apk: Add `cargo apk version` command for querying release version

---

cargo-apk/CHANGELOG.md
cargo-apk/Cargo.toml

Environment variables can be set and override the process environment through `.cargo/config.toml`'s `[env]` section: https://doc.rust-lang.org/cargo/reference/config.html#env
These config variables have specific precedence rules with regards to overriding the environment set in the process, and can optionally represent paths relative to the parent of the containing `.cargo/` folder.  The entire handling of these variables is implemented in https://github.com/dvc94ch/cargo-subcommand/pull/12 and https://github.com/dvc94ch/cargo-subcommand/pull/16 which immediately populate the process environment with these variables when `Subcommand::new()` is called by `cargo-apk`.

cargo-apk: Upgrade to `cargo-subcommand 0.7.0` for `[env]` support

---

ndk/src/media/media_codec.rs
ndk/src/media/mod.rs

These functions return a pointer directly instead of an error code with the pointer as argument, making them unsuitable for use with `construct_never_null`.  Because there is no error code, returning a manual success value still requires an infallible `unwrap()` call to unpack the `Result`.
Replace this with a new helper function that does not unnecessarily wrap the resulting pointer in a `Result` when there is no result code to base this off, and match the signature to a function that returns the pointer directly.
At the same time reduce the size of some `unsafe {}` blocks to wrap just what is unsafe.

media/media_codec: Replace `construct_never_null` and infallible `unwrap()` pattern with something more sensible

---

ndk-context/CHANGELOG.md
ndk-context/src/lib.rs
ndk-glue/CHANGELOG.md
ndk-glue/src/lib.rs

Fixes #261
Android runs multiple activities of the same app inside the same process, and shutting down followed by starting a `NativeActivity` inside the same process (that's been kept alive by another activity) causes the `static ANDROID_CONTEXT` in `ndk-context` to retain its value.  This value should be cleared to prevent leaking possibly invalid pointers and ultimately crashing in `assert!(previous.is_none());` when a native activity is restarted within that process.
Note that this still doesn't allow for multiple `NativeActivity` instances to be started concurrently.

ndk-glue,ndk-context: Remove `AndroidContext` when activity is destroyed

---

ndk-context/CHANGELOG.md
ndk-context/Cargo.toml
ndk-glue/CHANGELOG.md
ndk-glue/Cargo.toml

And prepare the changelogs for ndk-glue-0.4.2 and ndk-glue-0.5.2, whose backports will be processed in the respective stable branches.

Release ndk-context-0.1.1, ndk-glue-0.6.2

---

ndk-glue/src/lib.rs
ndk/CHANGELOG.md
ndk/src/media/media_codec.rs
ndk/src/native_window.rs

Much like ALooper and AHardwareBuffer the reference counter of ANativeWindow must be properly incremented on `Clone`, in turn allowing us to also `_release` the window as soon as it is dropped.

ndk/native_window: Use `release`/`acquire` fns for `Drop` and `Clone`

---

cargo-apk/CHANGELOG.md
cargo-apk/src/apk.rs

Fixes #265, CC @mercesa
Any flags passed directly to `cargo rustc` will only be passed _to the final compiler invocation_.  However `cdylib` library targets in transitive (dependency) crates will still be built (despite not being used in the final binary, that's what `rlib`s are for), but our NDK r23 workaround flags will not reach these compiler invocations rendering b912a6b ("cargo-apk: Work around missing libgcc on NDK r23 with linker script (#189)") ineffective.
[The same page] that documents this discrepancy suggests to resort to `RUSTFLAGS` if arguments are intended for all compiler invocations, which is our intended use-case and unblocks builds with transitive `cdylib` dependencies such as `hyper` in [#265].
[The same page]: …

cargo-apk: Reimplement NDK r23 `-lgcc` workaround using `RUSTFLAGS`

---

ndk/src/native_window.rs

`ANativeWindow` is the C counterpart to the `android.view.Surface` object in Java, and has these functions available to convert between the C and Java (JNI representation) variant of it.

ndk/native_window: Add bindings to convert to and from Java `Surface` representation

---

ndk-sys/Cargo.toml
ndk-sys/src/lib.rs
ndk/CHANGELOG.md
ndk/Cargo.toml
ndk/src/audio.rs
ndk/src/lib.rs

All the the other Android APIs implemented in the `ndk` crate drop the `A` prefix since this is already implied by the "namespace" of the NDK; there is no need to differentiate in Rust to prevent clashes with similarly named common symbols.

ndk: Rename `aaudio` to `audio` and drop `A` prefix

---

ndk/CHANGELOG.md
ndk/Cargo.toml
ndk/src/native_window.rs

Crates wrapping the NDK (winit and others), and `NativeWindow` in particular have to implement `HasRawWindowHandle` on their own wrapper types, yet the `ndk` should also implement this trait on the `NativeWindow` type directly for them to reuse.  Or more importantly, when the "raw" `ndk` crate is used directly.

ndk: Implement `HasRawWindowHandle` directly on `NativeWindow`

---

ndk/CHANGELOG.md
ndk/src/native_activity.rs

These functions return a path, which is slightly more ergonomic to handle when actually returned as an `std::path::Path` type instead of a `CStr`.
---
Unsure if this is actually the correct handling for going from a `CStr` -> `OsStr` (`Path`), but it seems to make sense / be correct since I don't think Unix requires paths to be UTF-8 (and go through ie. `&str`).

ndk/native_activity: Replace `CStr` return types with `Path`

---

ndk/CHANGELOG.md
ndk/src/hardware_buffer.rs
ndk/src/hardware_buffer_format.rs
ndk/src/lib.rs
ndk/src/native_activity.rs
ndk/src/native_window.rs

Android's `NativeWindow` allow querying the format through `ANativeWindow_getFormat` and setting it through `ANativeWindow_setBuffersGeometry` together with the dimensions to use for the buffer.

native_window: Add `format()` getter and `set_buffers_geometry()` setter

---

ndk/CHANGELOG.md
ndk/src/native_activity.rs

Depends on #276
Allows setting the window format before a window is created, directly through the `NativeActivity`.

native_activity: Add `set_window_format()` setter

---

ndk/CHANGELOG.md
ndk/src/native_activity.rs

Based on top of #276 and #277.
For example adding the `FULLSCREEN` flags allows hiding the status bar that otherwise draws over any fullscreen app.

native_activity: Add `set_window_flags()` to change window behaviour

---

ndk-glue/Cargo.toml
ndk-glue/src/lib.rs

Piggybacking on the [motivation in winit]: `lazy_static!` is a macro whereas `once_cell` achieves the same using generics.  Its implementation has also been [proposed for inclusion in `std`], making it easier for us to switch to a standardized version if/when that happens.  The author of that winit PR is making this change to many more crates, slowly turning the scales in favour of `once_cell` in our dependency tree too.
Furthermore `lazy_static` hasn't published any updates for 3 years, and the new syntax is closer for dropping this wrapping completely when the necessary constructors become `const` (i.e. switching to `parking_lot` will give us a [`const fn new()` on `RwLock`]) or this feature lands in stable `std`.
[motivation in winit]: https://github.com/rust-windowing/winit/pull/2313 …

ndk-glue: Replace ancient `lazy_static` crate with `once_cell`

---

cargo-apk/CHANGELOG.md
cargo-apk/src/apk.rs
ndk-build/CHANGELOG.md
ndk-build/src/cargo.rs

Winit is currently being hit by `-lgcc not found` linker errors because GH Actions' [virtual-environments recently migrated to Android NDK r23], and it turns out it's using the niche `--` subcommand to invoke regular `cargo` commands under an NDK environment.
The workaround using `RUSTFLAGS` is only patched into the `build()` command; by moving it into our `cargo_ndk()` environment preparation function this workaround is universally available and usable.
Note that this is a breaking change, we're changing the API signature of `ndk-build`.
[virtual-environments recently migrated to Android NDK r23]: https://github.com/actions/virtual-environments/issues/5595

cargo-apk,ndk-build: Move NDK r23 `-lgcc` workaround to `cargo_ndk` to reuse in `--` subcommand

---

cargo-apk/CHANGELOG.md
cargo-apk/src/apk.rs
ndk-build/CHANGELOG.md
ndk-build/src/apk.rs

As suggested in #153:
Compressing multi-megabyte libraries in `aapt` is a singlethreaded process that takes many (tens of) seconds, for no apparent gain.  It slows down the iterative development process significantly whereas there's no concern for `adb` transferring larger `apk`s over even USB 2.0 (which is still much faster than the bandwidth `aapt` provides for compression) nor typically any space constraints on development devices.

ndk-build,cargo-apk: Disable `aapt` compression for the `dev` profile

---

cargo-apk/CHANGELOG.md
cargo-apk/src/apk.rs

Depends on #286, #283
When the user doesn't provide a `--target` we default the triple to the currently connected device over `adb`, or otherwise fall back to `aarch64`.
While this triple is always used to determine what NDK environment to provide, it's never added to the arguments passed after `--`; for example a `cargo apk -- test --no-run` will try to build tests for the host unless explicitly called with `--target`.
---
I can't currently think of any command that one might want to run under `cargo apk --` with an NDK environment, but without support for `--target`. If there is, that's a valid argument to not pass this flag (but perhaps clearly document it, maybe even warn about it if we don't find `--target` in the call?).

cargo-apk: Append `--target` to blanket `cargo apk --` calls when not provided

---

ndk-glue/src/lib.rs
ndk-sys/src/lib.rs
ndk/CHANGELOG.md
ndk/src/asset.rs
ndk/src/audio.rs
ndk/src/bitmap.rs
ndk/src/configuration.rs
ndk/src/event.rs
ndk/src/hardware_buffer.rs
ndk/src/hardware_buffer_format.rs
ndk/src/input_queue.rs
ndk/src/lib.rs
ndk/src/looper.rs
ndk/src/media/image_reader.rs
ndk/src/media/media_codec.rs
ndk/src/native_activity.rs
ndk/src/native_window.rs

Instead of having an outdated overview of modules and their contents in the library documentation, move this to the module documentation header.  Rustdoc already provides a clickable link for every module (these manual list didn't include _any_ links), and also includes the first sentence/paragraph from this module documentation.
This also inserts some missing `struct` documentation and cleans up existing references to link to the NDK docs more often and specify exactly what type it is wrapping, instead of linking to the "rather useless" `ffi` representation for that NDK type.

ndk: Move library documentation to modules

---

ndk-examples/examples/looper.rs
ndk/CHANGELOG.md
ndk/src/input_queue.rs

These `AInputQueue` functions all return [standard `errno.h` error codes] which can and should be communicated back to the user instead of appearing as some opaque magic struct.
In addition import the NDK documentation for all these functions and make the scope of `unsafe` blocks smaller.
[standard `errno.h` error codes]: https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/jni/android_view_InputQueue.cpp;l=112;drc=7b3193e1e86ab5c0fcb784cb8616864045dd2515

ndk/input_queue: Replace `InputQueueError` with `std::io::Error` and add missing docs

---

ndk-glue/src/lib.rs
ndk/src/native_activity.rs

It has been quite some time since we introduced this, and our alternative implementation for more safely passing a native activity to the user while interoperating cleanly with `ndk_context` still hasn't found its way.
There are legitimate uses for `native_activity()` that cannot be performed through the suggested `ndk_context::android_context().vm()`, making the load of this deprecation warning heavier than the problem it tries to prevent.

ndk-glue: Drop `deprecated` annotation from `native_activity()`

---

ndk-build/CHANGELOG.md
ndk-build/src/cargo.rs

On Windows user paths usually include people's full name, with a space. If they have their Rust project somewhere in their user profile `cargo` fails to parse the workaround path:
process didn't exit successfully: `rustc - --crate-name ___ --print=file-names -L '"C:\Users\Bla' 'Haj\Desktop\Breda\target\cargo-apk-temp-extra-link-libraries"' ... (exit code: 1)
As per the [documentation for `RUSTFLAGS`] its contents are split by a very simple `.split(" ")` algorithm without caring for quotation delimiters or escape characters. To retain backwards compatibility this has been implemented in a new environment variable named `CARGO_ENCODED_RUSTFLAGS`, which separates by ASCII Unit Separators (`0x1f`) instead.
[documentation for `RUSTFLAGS`]: …

ndk-build: Switch NDK r23 -lgcc workaround to `CARGO_ENCODED_RUSTFLAGS` env var for paths with spaces

---

ndk-build/CHANGELOG.md
ndk-build/src/apk.rs
ndk-build/src/cargo.rs
ndk-build/src/error.rs
ndk-build/src/lib.rs
ndk-build/src/ndk.rs

The NDK's wrapper scripts for `clang`/`clang++` currently only, and will only ever pass `--target` to the compiler.  That is something we can do ourselves, especially now that we're already updating `RUSTFLAGS` anyway.
[Upstream even clarified] that it is recommended to pass `--target` yourself instead of incurring extra overhead while going through the wrapper scripts (especially costly on Windows), further guaranteeing that we won't miss out on any flags possibly being added to the wrapper scripts in the future.
[Upstream even clarified]: https://r.android.com/2134712

ndk-build: Invoke `clang` directly instead of through wrapper scripts

---

cargo-apk/CHANGELOG.md
cargo-apk/README.md
cargo-apk/src/apk.rs
cargo-apk/src/error.rs
cargo-apk/src/manifest.rs
ndk-build/src/ndk.rs

All builds currently use a fixed debug keystore.  This is cumbersome on machines where `keytool` isn't installed, and odd for `release` builds.
To make sharing debug APKs more consistent across developers this allows them to check in their `debug.keystore` in a repository and reuse it for everyone.
At the same time there's no sensible default-debug keystore for release builds; these require explicit configuration through the manifest (yet nothing withholds the user from passing their debug keystore here, if they so desire - but at least it's explicit).

cargo-apk: Configure APK signing keystore location through manifest

---

cargo-apk/CHANGELOG.md
cargo-apk/Cargo.toml
cargo-apk/src/apk.rs
ndk-build/CHANGELOG.md
ndk-build/Cargo.toml
ndk-build/src/manifest.rs

Fixes #304, CC @hoodad
We commonly name vectors of items with their singular form so that they read nicer in TOML and XML (i.e. `[[intent_filter]]` adds a single entry to that list, and gets serialized as a single `<intent-filter>` XML element) and this matches Android's `intent-filter` naming too.
This change in a6f3e13 ("ndk-build: Move default serialization of `MAIN` intent filter to `cargo-apk` (#241)") was made purely with `Vec` in mind, but breaks existing manifest parsing nor was anticipated to be a breaking change in this area as the README still carries `intent_filter` instead of `intent_filters` in its `Cargo.toml` metadata reference.
---
I want to try landing this without yet-another breaking release for `ndk-build`: can we do that by yanking the previous releases? We don't …

ndk-build,cargo-apk: Rename `intent_filters` back to `intent_filter`

---

ndk-examples/examples/looper.rs
ndk/CHANGELOG.md
ndk/src/input_queue.rs

After having blindly retained error handling in #292, it turns out the underlying [`InputQueue::hasEvents()` implementation] doesn't ever return an error nor does the documentation state that this is possible.
As such, mimic what we're already doing in `fn pre_dispatch()` and panic if the value doesn't represent a `bool`.
[`InputQueue::hasEvents()` implementation]: https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/jni/android_view_InputQueue.cpp;l=88-91;drc=5497dd365e9135805636a40267cb98e2e2b78ee6

ndk/input_queue: Remove `Result` wrapping from `has_events()`

---

ndk-glue/Cargo.toml
ndk-glue/src/lib.rs
ndk-macro/Cargo.toml
ndk-macro/src/lib.rs
ndk-sys/Cargo.toml
ndk-sys/src/lib.rs
ndk/Cargo.toml
ndk/src/lib.rs

The documentation currently doesn't expose what features a user needs to enable before certain functionality becomes available, requiring them to look at the sourcecode as we don't really provide much documentation or guideance towards this.
That's totally fine because it is a job for `rustdoc`, one that it performs very well when the experimental `doc_cfg` feature is enabled, and specifically `doc_auto_cfg` to not have to manually re-specify every `#[cfg(<guard>)]` within a `#[cfg_attr(docs_rs, doc(cfg(<guard>)))]`.
docs.rs builds on `nightly` which makes this possible, and docs can be built with the `docsrs` cfg enabled locally to see the result, e.g.:
RUSTDOCFLAGS="-Dwarnings --cfg docsrs" cargo +nightly doc --no-deps --workspace --target aarch64-linux-android --all-features …

Enable `doc_cfg` and `doc_auto_cfg` for all `[features]` crates on https://docs.rs

---

ndk/CHANGELOG.md
ndk/src/hardware_buffer.rs
ndk/src/input_queue.rs
ndk/src/lib.rs
ndk/src/native_window.rs
ndk/src/surface_texture.rs
ndk/src/utils.rs

Depends on #294
These `AHardwareBuffer` functions all return [standard `errno.h` error codes] which can be communicated back to the user in ergonomic form instead of appearing as a newtyped struct holding a "meaningless" `i32`.
Perform the same conversion to just `NativeWindow::set_buffers_geometry` which also returns `errno.h` codes: this change is small enough to not warrant _yet another_ PR, as we've already changed the exact same for `InputQueueError` in [#292].  (Note that this is intentionally omitted from the changelog since `set_buffers_geometry()` is only making its debut in the upcoming release, this change isn't breaking).
This pattern is now prevalent across the codebase (`hardware_buffer`, `surface_texture`, and `native_window` all use it), warranting the new …

ndk: Replace `HardwareBufferError` with `std::io::Error` through new helper conversion function

---

ndk/CHANGELOG.md
ndk/src/bitmap.rs
ndk/src/hardware_buffer.rs
ndk/src/media/image_reader.rs

Depends on #294, #295
According to [`AndroidBitmap_getHardwareBuffer`]:
outBuffer   On success, is set to a pointer to the AHardwareBuffer
associated with bitmap. This acquires a reference on the
buffer, and the client must call AHardwareBuffer_release
when finished with it.
By returning the `outBuffer` wrapped in `HardwareBuffer` we represent a weak instead of strong reference, and don't `_release` it on `Drop`.  If we instead wrap it in a `HardwareBufferRef` we get the desired `release` semantics on `Drop` and prevent resource leaks for the user.
Note that a similar API on [`AImage_getHardwareBuffer`] does **not** aquire a strong reference, and should remain returning a weak `HardwareBuffer`.
This feat isn't very well described in the docs, so we now echo what was only stated on …

ndk: Fix `HardwareBuffer` leak for `AndroidBitmap` and clarify handling in docs

---

ndk-glue/CHANGELOG.md
ndk-glue/src/lib.rs

As recently recommended/requested, this prevents `ndk_glue` from leaking its underlying lock implementation, and relieves downstream crates from having to import and specify the appropriate lock type.  Especially in light of a scheduled migration to `parking_lot`.
Note that this won't prevent against API breakage introduced by the intended change of transposing the `Option` inside this `LockReadGuard` as that can't be done prior to switching to `parking_lot`, and it'll be its own free-standing API ergonomics improvement regardless (`Option` now only needs to be unwrapped/checked once).
Finally add some more doc-comments to link to the new lock and explain how the locks should be used on the `*Created` events and getter functions too, instead of describing it only on the `*Destroyed` …

ndk-glue: Wrap `NativeWindow`/`InputQueue` locks in a newtype

---

ndk-glue/CHANGELOG.md
ndk-glue/Cargo.toml
ndk-glue/src/lib.rs

Depends on #282
It has come up previously that the `native_window()` function is easier to use if we could transpose a `LockGuard<Option<>>` into an `Option<LockGuard<>>`.  After all, as soon as you have the lock you only need to check the `Option<>` value once and are thereafter guaranteed that its value won't change, until the lock is given up.
At the same time `parking_lot` has a `send_guard` feature which allows moving a lock guard to another thread (as long as `deadlock_detection` is disabled); a use case for this recently came up [in glutin] where the `NativeWindow` handle lock should be stored with a GL context so that our `fn on_window_destroyed()` callback doesn't return until after the `Surface` created on it is removed from the context and destroyed.  Glutin forces this context …

ndk-glue: Switch to `parking_lot` for `map`pable and `Send`able lock guards

---

ndk/CHANGELOG.md
ndk/src/media/media_codec.rs

For rendering outside a surface, you can pass a null in the C++ bindings, so translate this to a `None` in Rust side.
https://developer.android.com/reference/android/media/MediaCodec#configure(android.media.MediaFormat,%20android.view.Surface,%20android.media.MediaCrypto,%20int)

media_codec: `NativeWindow` can be optional in `fn configure()`

---

ndk-glue/src/lib.rs
ndk-sys/CHANGELOG.md
ndk-sys/generate_bindings.sh
ndk-sys/src/ffi_aarch64.rs
ndk-sys/src/ffi_arm.rs
ndk-sys/src/ffi_i686.rs
ndk-sys/src/ffi_x86_64.rs
ndk/src/hardware_buffer.rs
ndk/src/hardware_buffer_format.rs
ndk/src/media/image_reader.rs

Searching for `pub type` reveals a lot of typedefs for enums that could have been a newtype with associated constants.  Unfortunately there are still a lot of private enums in the source, some with a `typedef` following: these cannot be converted yet, otherwise we might have gotten away with globally enabling `--default-enum-style` to apply this style to _every_ enum.
At the same time certain enums could use `--bitfield-enum` yet those eligible also suffer from the same lack of a type, requiring the user to work with `_bindgen_ty_XX` which is far from ergonomic.

ndk-sys: Switch remaining enums to newtypes with associated constants

---

ndk-examples/Cargo.toml
ndk/CHANGELOG.md
ndk/Cargo.toml
ndk/src/bitmap.rs
ndk/src/hardware_buffer.rs
ndk/src/media/image_reader.rs
ndk/src/trace.rs

Fixes #318
Thus far feature flags have been used specifically in `ndk-sys` to control what native libraries are linked to, for content that is provided outside of the standard linked `libandroid.so`:
https://github.com/rust-windowing/android-ndk-rs/blob/d104d01f116b537babdc94d8c9889581f8d63a02/ndk-sys/src/lib.rs#L43-L53
However, `hardware_buffer` and `trace` are available in `libandroid.so` directly making these features only guard our Rust bindings.  This is unnecessarily tedious and inconsistent with the rest of the NDK wrappers which are only guarded by their minimum API level.

ndk: Remove "irrelevant" `hardware_buffer`/`trace` feature in favour of API level

---

ndk-glue/CHANGELOG.md
ndk-glue/Cargo.toml
ndk-sys/CHANGELOG.md
ndk-sys/Cargo.toml
ndk/CHANGELOG.md
ndk/Cargo.toml

Almost over the finish line!  Still have a few things to clean up, but we can unblock `winit 0.27` really soon!

Release ndk-sys-0.4.0, ndk-0.7.0, ndk-glue-0.7.0

---

cargo-apk/CHANGELOG.md
cargo-apk/src/apk.rs
ndk-build/CHANGELOG.md
ndk-build/src/apk.rs
ndk-build/src/readelf.rs

Builds on #246 but cleans it up a bit. 
We started to run into this since the Vulkan-SDK started building with `libc++_shared.so` in https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/a64eec06b8a155c8deb3f27411c4a322faa95e9f

Deduplicate all (recursively) added runtime libraries

---

cargo-apk/CHANGELOG.md
cargo-apk/README.md
ndk-build/src/manifest.rs

This is a trivial pull request to add support for the [`android:resizeableActivity`](https://developer.android.com/guide/topics/manifest/activity-element#resizeableActivity) attribute on `<activity>`, needed e.g. for [manifests for the Oculus Quest](https://developer.oculus.com/documentation/native/android/mobile-native-manifest/) VR headset.

ndk-build: Support `android:resizeableActivity`

---

ndk-sys/CHANGELOG.md
ndk/CHANGELOG.md
ndk/src/event.rs

I'm working on a PR for winit that adds stylus support for Windows and Android.
This getter is required to differentiate between touch, mouse and stylus inputs consistently.

ndk: Add `tool_type` getter for `Pointer` events

---

cargo-apk/CHANGELOG.md
cargo-apk/src/apk.rs
cargo-apk/src/main.rs
ndk-build/CHANGELOG.md
ndk-build/src/apk.rs
ndk-build/src/ndk.rs

This feels quite hacky, but it doesn't look like cargo_subcommand has adequate functionality to filter or add new arguments to some of the commands. 
This adds support for a `--device` arg in both `cargo apk run` and `cargo apk gdb` to run on a specific device whenever one is present.

Add --device arg to be able to run on specific android devices

---

ndk-build/src/apk.rs
ndk-build/src/error.rs

Depends on  #329 to apply cleanly.
Shows the process PID after launching. Requires `-W` as an `am start` arg to wait for process completion to prevent a race condition. Having the PID is useful in a lot of cases, such as filtering logs with `adb logcat --pid=...`

ndk-build: Return PID after launching the app

---

.github/workflows/android_test.sh
cargo-apk/CHANGELOG.md
cargo-apk/src/apk.rs
cargo-apk/src/main.rs
ndk-build/CHANGELOG.md

Depends on #331
This starts a logcat session for our PID so we have something that's a bit more akin to how `cargo run` regularly works. If this is undesired, I would also be OK with adding a `--log` argument.

cargo-apk: Print and follow `adb logcat` output after starting app

---

cargo-apk/src/apk.rs
ndk-build/CHANGELOG.md
ndk-build/src/lib.rs
ndk-build/src/ndk.rs

The path to the gdb script wasn't generated properly (was missing the `.cmd` extension) and the `detect_abi` was similarly broken on windows.

ndk-build: Add `ndk_gdb()` function to acquire `ndk-gdb` script path with the correct per-platform extension

---

cargo-apk/src/apk.rs

`ndk-gdb` must use the same device as `.run()` previously launched the app on.

cargo-apk: Pass device serial to `ndk-gdb`

---

cargo-apk/src/main.rs

The terminal must be available for GDB to start and interact with, instead of indefinitely blocking on a running instance of `logcat`.

cargo-apk: Force-disable logcat in `fn run()` when using `gdb`

---

cargo-apk/src/apk.rs
ndk-build/CHANGELOG.md
ndk-build/src/ndk.rs

Depends on #257
Just a draft for now as I haven't really tested this on Windows yet - but the missing `.cmd` is obvious enough, and this command is probably useful to expose from the `ndk-build` library anyway.

cargo-apk,ndk-build: Move `ndk-gdb` setup to `ndk-build` and support Windows

---

ndk-build/CHANGELOG.md
ndk-build/src/ndk.rs

`adb` is not necessarily available in `PATH`, hence why `cargo-apk` and `ndk-build` detect and use this executable from the SDK path.  We should do the same for `ndk-gdb` which strangely doesn't search for `adb` within the SDK it resides in.

ndk-build: Provide `adb` path to `ndk-gdb`

---

ndk-build/CHANGELOG.md
ndk-build/src/ndk.rs

On Windows it seems the `ndk-gdb.py` script that invokes `make` to dump the variables from `Android.mk` fails to strip quotation marks from the file correctly, resulting in erroneous output like (notice double quotes at the end of the path):
OSError: [WinError 123] The filename, directory name, or volume
label syntax is incorrect:
'android-ndk-rs\\target\\debug\\apk\\examples\\""'
And:
Application cannot run on the selected device.
Application ABIs: "arm64-v8a"
Device ABIs: arm64-v8a, armeabi-v7a, armeabi
Solve this by removing the quotes, allowing `ndk-gdb` to launch sucessfully.

ndk-build: Remove unparsable quotes from `Android.mk` for `ndk-gdb`

---

cargo-apk/src/apk.rs
cargo-apk/src/main.rs
ndk-build/CHANGELOG.md
ndk-build/src/ndk.rs

`ndk-gdb` passes `-D` to `am start` to make the process wait until the debugger is launched and ready, instead of possibly crashing the app before the debugger can catch it (paired with a nice "waiting for debugger" dialog and "Force close" button in Android).  While we could also set the flag ourselves, this change simplifies the workflow on our end as well now that we don't have to run our own command, potentially get stuck on `pidof` returning multiple PIDs, and having to override `no_logcat` (#342).
(For the multiple-PID case though, we can optionally pass `-f` to make `ndk-gdb` kill the debugger and app first, if this ever becomes an issue.)

ndk-build,cargo-apk: Launch activity directly through `ndk-gdb`

---

ndk-build/CHANGELOG.md
ndk-build/src/ndk.rs

Fixes https://github.com/rust-windowing/android-ndk-rs/issues/327, CC @Hoodad
According to the [official documentation] `ndk-build` is considering the wrong variable as deprecated.  The wrong message was introduced in [#39] which bizarrely failed to quote any reference matterial on the matter, making it impossible to understand whether this has always been the case or recently switched in precedence.
[official documentation]: https://developer.android.com/studio/command-line/variables
[#39]: https://github.com/rust-windowing/android-ndk-rs/pull/39

ndk-build: Consider ANDROID_SDK_ROOT as deprecated instead of ANDROID_HOME

---

ndk-build/CHANGELOG.md
ndk-build/src/ndk.rs

Use the [documented environment variables] to determine the location of `$HOME/.android`, instead of hardcoding it to reside under `$HOME`.
[documented environment variables]: https://developer.android.com/studio/command-line/variables#envar

ndk-build: Read ANDROID_USER_HOME and ANDROID_SDK_HOME env for `$HOME/.android` folder

---

ndk-build/src/ndk.rs
ndk/src/media/media_codec.rs

Rust 1.64 is a bit more strict on requiring `.then_some(...)` here over `.then(|| ...)` with a closure, but the former has only been stabilized in 1.62.  No need to be cocky and bump the MSRV, replace it with an `if`-`else` like the rest of the `.exists()` path-checking code around here.

Fix `clippy::unnecessary_lazy_evaluations` since Rust 1.64

---

cargo-apk/README.md
cargo-apk/src/apk.rs
cargo-apk/src/manifest.rs
ndk-build/src/apk.rs

This adds a feature so we can set up reverse port forwarding from our Cargo.toml file before the app starts
```toml
[package.metadata.android.reverse_port_fwd]
"tcp:1338" = "tcp:1338"
"tcp:1339" = "tcp:1339"
```

cargo-apk: Automate `adb reverse` port forwarding through `Cargo.toml` metadata

---

README.md

NDK r25 works just as well as r24, and is the current LTS.  There are no other releases planned between it and r26 launching in 2023, and scheduled to be the next NDK.
The mention of our workaround is irrelevant given that it's something we deal with for the user in the background, and the feature has evolved many times through multiple PRs.  This allows us to drop the beta notion for r23 which is long deprecated by now.

readme: Document compatibility with NDK r25 and remove workaround mention

---

cargo-apk/CHANGELOG.md
cargo-apk/README.md
cargo-apk/src/apk.rs
cargo-apk/src/manifest.rs
ndk-build/CHANGELOG.md
ndk-build/src/apk.rs
ndk-build/src/ndk.rs

In the cargo-apk docs, it has
```ini
[package.metadata.android.signing.<profile>]
path = "$HOME/.android/debug.keystore"
keystore_password = "android"
```
But the `$HOME` is a lie, cargo-apk doesn't actually expand environment variables, this change just adds a _very_ simple and dumb expansion, only if an environment variable is present at the beginning, and it actually exists.

Read keystore path/password from env vars prior to package metadata

---

ndk-build/CHANGELOG.md
ndk-build/src/cargo.rs

When running the actual cargo build, the `CARGO_ENCODED_RUSTFLAGS` was being read so that the rustflags set by the user are not overwritten when cargo-apk is adding its flags. However, this environment variable will only be set if you are building the APK via a build script, if you are invoking `cargo apk build` cargo will not create that environment variable since it doesn't know what actual target/profile is going to be built. If `CARGO_ENCODED_RUSTFLAGS` is not found, this change now falls back to `RUSTFLAGS`, and interprets it the same as `cargo` does before writing it in the encoded form expected by `CARGO_ENCODED_RUSTFLAGS`

nkd-build: Propagate `RUSTFLAGS` into `CARGO_ENCODED_RUSTFLAGS`

---

cargo-apk/CHANGELOG.md
cargo-apk/README.md
cargo-apk/src/apk.rs
cargo-apk/src/manifest.rs
ndk-build/CHANGELOG.md
ndk-build/src/apk.rs
ndk-build/src/cargo.rs

I've been extremely annoyed with the time that `cargo-apk` adds onto our build for a long time and today was the day that I got annoyed enough to fix it.
This PR adds a configuration field, `package.metadata.android.strip` that allows users to configure how they want to treat debug symbols _after_ cargo build has finished, but _before_ the .so libraries are appended to the APK.
- `default` - This acts the exact same as the current version of cargo-apk, and is the value used if `strip` is not explicitly set. The .so produced by cargo is simply copied to the `apk` output directory with no modification.
- `strip` - The library copied into the apk output directory is stripped of debug symbols
- `split` - The library copied into the apk output directory is stripped of debug symbols, in …

cargo-apk: Add `strip` configuration to manifest

---

cargo-apk/src/apk.rs

Rust 1.65 stepped up its `clippy::needless_borrow` game around types and their borrows implementing a certain trait, realizing that `&PathBuf` already implements `AsRef<Path>` and doesn't need to be reborrowed as `&&PathBuf`.

cargo-apk: Fix improved `clippy::needless_borrow`

---

ndk-examples/Cargo.toml
ndk-examples/examples/jni_audio.rs

Fixes #364
Bump the `jni` dep for `ndk-examples` to 0.20.

ndk-examples: Update `jni` dependency to `0.20`

---

.github/workflows/rust.yml
README.md
cargo-apk/Cargo.toml
ndk-build/Cargo.toml
ndk-context/Cargo.toml
ndk-glue/Cargo.toml
ndk-macro/Cargo.toml
ndk-sys/Cargo.toml
ndk/Cargo.toml

CC @kchibisov
Prevent inadvertently bumping MSRV in PRs by checking against MSRV in the CI, to disallow any large bumps without rationale.  Rust 1.60 is 7 months old at the time of writing, and also required by `winit` which uses `android-ndk-rs`, hence must be compatible with it.
This does not mean that we cannot bump MSRV at all, but we must remain a tad conservative; at the same time setting [`rust-version`] in the manifest provides everyone on Rust 1.56 and higher a helpful error message when their version is lower than what we require.
[`rust-version`]: https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field

Lock MSRV to 1.60 and validate in CI

---

ndk-sys/Cargo.toml
ndk-sys/generate_bindings.sh
ndk-sys/src/ffi_aarch64.rs
ndk-sys/src/ffi_arm.rs
ndk-sys/src/ffi_i686.rs
ndk-sys/src/ffi_x86_64.rs
ndk/src/bitmap.rs

Note that an `enum` suffix had to be added to `AMidi.h` to prevent `bindgen` from erroring out on (EDIT: reported upstream at https://github.com/android/ndk/issues/1739):
~/Android/Sdk/ndk/25.0.8775105/toolchains/llvm/prebuilt/linux-x86_64/sysroot//usr/include/amidi/AMidi.h:230:1: error: must use 'enum' tag to refer to type 'AMidiDevice_Protocol'
~/Android/Sdk/ndk/25.0.8775105/toolchains/llvm/prebuilt/linux-x86_64/sysroot//usr/include/amidi/AMidi.h:230:1: error: must use 'enum' tag to refer to type 'AMidiDevice_Protocol', err: true
thread 'main' panicked at 'Unable to generate bindings: ()', src/main.rs:52:36
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Also list this NDK version in the `ndk-sys` version metadata, exposing it on …

ndk-sys: Regenerate against NDK r25.0 (build 8775105)

---

ndk/CHANGELOG.md
ndk/src/input_queue.rs

Fixes #322
Despite the [Android source] never returning anything other than `0` or `1` there appear to be platforms out in the wild that take [the documentation] quite literally and return vague non-zero codes apart `1` with a possible secondary meaning.
[Android source]: https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/jni/android_view_InputQueue.cpp;drc=b6d7f3b484e4c32c144c66bee342c29e7a8d34cc;l=115
[the documentation]: https://developer.android.com/ndk/reference/group/input#ainputqueue_predispatchevent

ndk/input: Allow any non-zero return in `pre_dispatch()` again

---

cargo-apk/src/apk.rs
cargo-apk/src/main.rs

`clap` [does not currently support] parsing unknown arguments into a side `Vec`, which is exactly what `cargo apk --` needs to parse a few known `cargo` arguments (such as `--target` and `-p`) but forward the rest verbatim to the underlying `cargo` subcommand.
`allow_hyphen_values = true` could partially help us out with this, but it parses all remaining arguments into that `Vec` upon encountering the first unknown flag/arg, resulting in all known flags after that to also be treated as "unknown" instead of filling up our `args: Args` struct.
Since [a workaround for this isn't currently functioning], introduce pure trailing args with an additional `--` separator to make it clear which arguments go to `cargo-apk` (and are almost all, except `--device`, forwarded to `cargo`) and which are …

cargo-apk: Reimplement "default" (`--`) subcommand trailing args for `cargo`

---

cargo-apk/CHANGELOG.md
cargo-apk/Cargo.toml
cargo-apk/src/apk.rs
cargo-apk/src/error.rs
cargo-apk/src/manifest.rs

Depends on https://github.com/dvc94ch/cargo-subcommand/pull/23, https://github.com/dvc94ch/cargo-subcommand/pull/24
Fixes #359
Starting with [Rust 1.64] common `[package]` parameters (and dependencies) can now be specified in the workspace root manifest by setting `<field>.workspace=true` in a `[package]` and specifying its value in the workspace root manifest under [`[workspace.package]`][1].
Since `cargo-apk` reads the `version` field from `[package]` it has to support this new format and pull the value from the root manifest instead, in order to support projects utilizing this new format.
This is currently implemented ad-hoc for the version field, but could be done in a cleaner way if/when more fields are needed.
[Rust 1.64]: https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html#cargo- …

cargo-apk: Inherit package configuration (`version`) from workspace root

---

ndk/src/asset.rs

While browsing these docs I could not click through to this function while it should obviously be very easy to jump to it.
Also reference the `.next()` function more appropriately.

ndk/asset: Make reference to `AssetManager::open()` an intradoc link

---

ndk/src/asset.rs

According to `AAsset_getBuffer` documentation:
Get a pointer to a buffer holding the entire contents of the assset.
This means the returned pointer points to the _start of_ the asset, and will thus be pointing to a memory range as long as the asset.  If the user had first read X bytes before mapping it as a buffer, there will now be X bytes cut off at the end of the buffer since `get_remaining_length()` returns `get_length() - X` at this point.

ndk/asset: Use entire asset length when mapping buffer

---

README.md

This is fairly ruthless with the previous guidance that was in the README but now that this repo has a much more narrow scope this strips the README back to just the essentials that relate to the NDK bindings.
This also adds sign posting for all the crates that were split out from this repo, considering that the original `android-ndk-rs` repo URLs will redirect here, and people may wonder where these crates have moved.

Update README to reflect modularization changes

---

ndk/Cargo.toml
ndk/src/native_activity.rs

This crate doesn't seem to have taken off (3 years since last update) against the `jni` and `jni-sys` crate, and the `ndk` only uses it for a single (compile-testable) documentation example.

ndk: Drop optional `jni-glue` dependency

---

ndk/Cargo.toml
ndk/src/looper.rs
ndk/src/native_activity.rs

Changelog: https://github.com/bitflags/bitflags/blob/2.0.0/CHANGELOG.md#200.
This is a breaking change. The API that is implemented by the macro is now different.

Bump `bitflags` to `2.0.0`

---

ndk/CHANGELOG.md
ndk/Cargo.toml

ndk: Upgrade `num_enum` crate from `0.5.1` to `0.6`

---

ndk/src/media/media_codec.rs
ndk/src/media/mod.rs

Back when I refactored these in #248 and #256 the closure argument should have been removed entirely as it is only called immediately without any arguments, so its return value could have been passed instead.  At that point the function becomes simple enough to warrant removal entirely, inlining the unwrap and even allowing a more natural string literal error message in `.expect()`.
CC @zarik5

ndk/media_codec: Inline `get_unlikely_to_be_null()`

---

ndk/CHANGELOG.md
ndk/src/lib.rs
ndk/src/media/image_reader.rs
ndk/src/media/media_codec.rs
ndk/src/media/mod.rs
ndk/src/media_error.rs

CC @paxbun
- Clean up the names: we're already in the `ndk` crate so no need to repeat that in the type name;
- Make the types available outside the `media` module, so that they can be used in `AMidi` bindings which are not located inside `libmediandk.so` (but `libamidi.so`);
- Add documentation comments;
- Guard `dead_code` helper functions with the right `feature` bound.

ndk: Rework media error types

---

ndk/CHANGELOG.md
ndk/src/media/media_codec.rs

Supersedes #316, CC @zarik5
Closes #316
The dequeue API for output buffers can commonly return `AMEDIACODEC_INFO_OUTPUT_FORMAT_CHANGED` or `AMEDIACODEC_INFO_OUTPUT_BUFFERS_CHANGED`, both of which are not caught in `NdkMediaError::from_status()` and show up as an "unknown" error.  Neither really is an error that the user would want to bubble up from the `Result<>` via `?`, but should rather handle this explicitly.
A similar case already exists for `AMEDIACODEC_INFO_TRY_AGAIN_LATER` which previously resulted in a `None`, but is now also encapsuled in a self-documenting manner, for the dequeue_input_buffer()` API as well.

ndk/media_codec: Wrap common dequeued-buffer status codes in enum

---

ndk/CHANGELOG.md
ndk/src/media/media_codec.rs

Depends on #401, CC @zarik5
The byte-array mapped/returned by `AMediaCodec_getInputBuffer()` is not known to be initialized as the caller requires this API to subsequently initialize the data, and mapping/casting uninitialized memory segments as safe data in Rust is Undefined Behaviour.  Instead, return a `MaybeUninit<u8>` type to be safe (as in: the user cannot *safely* read data in the returned slice, only write to it) and document the intent back to the user.
Unfortunately, as of writing many useful API around _slices of_ `MaybeUninit` are still unstable.

ndk/media_codec: Return `MaybeUninit` bytes in `buffer_mut()`

---

ndk/CHANGELOG.md
ndk/src/hardware_buffer_format.rs

These seem to have been added in the NDK r25 release.

hardware_buffer_format: Add `YCbCr_P010` and `R8_UNORM` variants

---

README.md
ndk/CHANGELOG.md
ndk/src/hardware_buffer_format.rs
ndk/src/native_activity.rs
ndk/src/native_window.rs

For https://github.com/rust-windowing/softbuffer/issues/44, CC @notgull

ndk/native_window: Add `lock()` to blit raw pixel data

---

ndk/CHANGELOG.md
ndk/src/hardware_buffer.rs
ndk/src/hardware_buffer_format.rs
ndk/src/native_activity.rs
ndk/src/native_window.rs

Hardware buffers can have private formats which don't appear in the NDK header. Add a catch-all variant to avoid panicking in `HardwareBuffer::describe()`.

hardware_buffer_format: Add catch-all variant

---

ndk/CHANGELOG.md
ndk/Cargo.toml
ndk/src/audio.rs
ndk/src/media/image_reader.rs
ndk/src/utils.rs

As discussed in #410. Mostly copied from the equivalent code in [android-activity](https://github.com/rust-mobile/android-activity/blob/96497f9da990c0006ff88076d06cc50a7870d1dc/android-activity/src/util.rs). Resolves #268.

Add panic guards to callbacks

---

ndk-sys/Cargo.toml
ndk/Cargo.toml
ndk/src/audio.rs
ndk/src/bitmap.rs
ndk/src/configuration.rs
ndk/src/event.rs
ndk/src/lib.rs
ndk/src/looper.rs
ndk/src/media/image_reader.rs
ndk/src/media/media_codec.rs
ndk/src/native_activity.rs
ndk/src/native_window.rs
ndk/src/surface_texture.rs
ndk/src/trace.rs

We've never cleaned up our code to utilize some Rust 2018 idioms.  And by bumping to 2021 we get a more elaborate prelude allowing us to drop `TryFrom`/`TryInto` imports.

Bump to edition 2021 and clean up 2018 idioms

---

ndk/CHANGELOG.md
ndk/src/looper.rs

We've previously only been able to unregister file descriptors by using a callback and returning `false` from it to be unregistered.  Add the missing method that allows users to unregister their file descriptors from the looper for any reason.
There has always been a "concern" about leaking the `Box` inside `add_fd_with_callback()`, but this is already very easy by never returning `false` from the callback or registering a different callback / event on the same `fd`, so this new function doesn't really expose that.

ndk/looper: Add `remove_fd()` method

---

ndk/CHANGELOG.md
ndk/src/media/media_codec.rs

Note that unlike the audio data callback, I do not provide a reference to the codec as a callback parameter. Happy to be overruled on this, but I find the notion of constructing a new `MediaCodec` which wraps an `ffi::AMediaCodec` already owned by another `MediaCodec` somewhere else to be a bit questionable. If you really need access to the `MediaCodec` within the callback than you can use a `Mutex` or something, but the reality is that you can't actually do very much within the callback. For example, if you try to release the output buffer in the 'output available' callback then the whole thing just deadlocks.
Typical usage might look something like this (sans proper error handling):
```rust
let (input_tx, input_rx) = channel(32);
let (output_tx, output_rx) = channel(32);
codec …
```

media_codec: Add support for asynchronous notification callbacks

---

ndk-sys/CHANGELOG.md
ndk-sys/Cargo.toml
ndk/CHANGELOG.md
ndk/Cargo.toml

Release ndk-sys-0.5.0-beta.0, ndk-0.8.0-beta.0

---

ndk/src/media/image_reader.rs

When implementing proper ownership `acquire()` and `release()` semantics for `NativeWindow` in https://github.com/rust-mobile/ndk/pull/207, I thought I had checked all existing calls to `NativeWindow::from_ptr()` to make sure that they return a pointer that we get ownership over, and have to clean up ourselves.  This turns out to [not be the case for `AImageReader_getWindow()`]:
The ANativeWindow is managed by this image reader. Do NOT call ANativeWindow_release on it. Instead, use AImageReader_delete.
And can be trivially reproduced by creating an `ImageReader` and calling `.get_window()`.  Dropping the `NativeWindow` is fine but subsequently dropping the `ImageReader` results in a NULL-pointer SEGFAULT.
For now calling `clone_from_ptr()` is enough to first acquire an extra reference on …

ndk/media/image_reader: Don't assume ownership of `NativeWindow`

---

ndk/src/media/media_codec.rs
ndk/src/media_error.rs

CC @paxbun
Covers a prevalent `unwrap_err()` pattern for negative status codes, where we want to use any non-negative status code as a useful value and otherwise assert that `from_status()` turns the raw value into an appropriate error code (never into `Ok(())`, which should be unreachable in the current implementation).
Note that we cannot rely on `from_status()` returning `Ok(())` or `Err(_)` and translate the `Ok(())` back to the original value, as it handles (as of writing) two positive error codes which only relate to a specific `AMediaCodec` API, and any unrecognized codes including >0 are treated as `UnknownStatus`.
The function consumes `Into<isize>` instead of `i32/c_int` or `ffi::media_status_t` to support passing through numbers from various APIs that return 64-bit numbers …

media_error: Add `MediaStatus::from_status_if_negative()` helper

---

ndk/CHANGELOG.md
ndk/src/hardware_buffer.rs
ndk/src/looper.rs
ndk/src/media/image_reader.rs

Depends on #416
Some functions consume a file descriptor (will close them on their own regard) or return ownership over a file descriptor (expect the caller to close it), but this is not always clarified in the documentation nor upheld by the caller.  Use the new stabilized `BorrowedFd` and `OwnedFd` types since Rust 1.63 to clarify this in the API, noting that `OwnedFd` will instinctively `close()` the file descriptor on drop and doesn't implement `Copy` nor `Clone` (but does provide a `try_clone()` helper using `fcntl()` to create a new owned file descriptor if needed, and if possible by the kernel).
For example, while not obvious from `AHardwareBuffer_lock()` docs (though there are hints in the [graphics sync docs]) the source for gralloc buffer locking many function calls down …

ndk: Use `BorrowedFd` and `OwnedFd` to clarify ownership transitions

---

ndk/CHANGELOG.md
ndk/src/asset.rs

These two functions are not exactly critical but may be useful to some developers.
`is_allocated()` tells us whether a backing buffer is created in RAM, or if the data is directly `mmap()`'ed from the APK (e.g. because no decompression was needed and alignment requirements are upheld).  Note that it only returns `true` after the asset is "mapped" (or read in some way) via e.g `get_buffer()`; solely opening the asset is not enough to trigger the allocation and decompression.
`open_file_descriptor()` gives the user a file descriptor, which simply seems to be a `dup()` of that from the opened APK, together with an offset and size of the given `AAsset` within that APK.  It also requires the asset to be stored uncompressed within the APK.

ndk/asset: Add missing `is_allocated()` and `open_file_descriptor()`

---

.github/workflows/publish.yml
.github/workflows/rust.yml

These containers spit more deprecation warnings than ever before, and should be replaced with simply invoking `cargo` directly.  That's much more relatable for users and all the necessary tools come preinstalled on GitHub's runner images anyway: https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#rust-tools
`rustup`-like `actions-rs/toolchain` calls are converted to `dtolnay/rust-toolchain` though, as this was already used for MSRV test installs.

GH Actions: Replace deprecated `actions-rs` with direct `run:`

---

ndk/src/looper.rs

As with #412 we shouldn't let panics unwind into the FFI boundary; use the new helper `abort_on_panic()` utility to catch these and abort the process instead.

looper: Also abort on panic in FFI callback

---

ndk/src/hardware_buffer.rs
ndk/src/input_queue.rs
ndk/src/native_window.rs
ndk/src/surface_texture.rs
ndk/src/utils.rs

We were unconditionally passing an `assume_init()` value to `status_to_io_result()`, which would only return that value back if there was no error.  This is UB if the `MaybeUninit` was never written to, which is typically the case when an error is returned.  Instead a `.map(|()| ...assume_init())` should be used to ensure we only move the `MaybeUninit` into an initialized Rust value when the error code says it is okay to do so.
As this is the only place where a non-void (`()`) value was passed to `status_to_io_result()`, the `value: T` argument has been removed in favour of always returning `()` just like the `BitmapError::from_status()` and `MediaError::from_status()` APIs.

ndk/hardware_buffer: Don't call `assume_init()` before checking error

---

ndk/CHANGELOG.md
ndk/Cargo.toml
ndk/src/hardware_buffer.rs

This is the only new/missing function in our `HardwareBuffer` wrapper, except the `AParcel` functions that cannot be bound until that type is mapped.

ndk/hardware_buffer: Add API-31 `getId()` function to `HardwareBuffer`

---

ndk/CHANGELOG.md
ndk/src/bitmap.rs

As per the TODO, wrap this flags type with some helpers that fish out the two bit-representations for the `IS_HARDWARE` flag and `ALPHA` value.
Also add missing documentation and aliases across the `bitmap` module.
CC @dcsommer since you most recently touched this module and are likely relying on it: can you give this a review?

ndk/bitmap: Provide detailed implementation for `AndroidBitmapInfoFlags`

---

.github/workflows/rust.yml
ndk/CHANGELOG.md
ndk/Cargo.toml
ndk/src/asset.rs
ndk/src/hardware_buffer.rs
ndk/src/hardware_buffer_format.rs
ndk/src/looper.rs
ndk/src/media/image_reader.rs
ndk/src/native_activity.rs
ndk/src/native_window.rs

It is older than 6 months and now required for the `toml_edit` dependency (used by `num_enum_derive`).  At the same time `num_enum` relies on arbitrary enum discriminants (for discriminated enums with tuple/struct variants) introduced by Rust 1.66 in order to implement `#[num_enum(catch_all)]`.  This feature comes in use to replace the manual `match` blocks when implementing conversions for `HardwareBufferFormat` when also having an `Unknown(u32)` to catch valid private/vendor values that won't ever be described inside the NDK.  This change effectively reverts #407 to its initial state, where a `catch_all` implementation was used.  CC @spencercw.
For the latter the intent is however to use this feature sparingly. In most APIs new values are few and far between, so treating these as an …

ndk: Bump MSRV from 1.64 to 1.66

---

ndk/CHANGELOG.md
ndk/Cargo.toml
ndk/src/audio.rs
ndk/src/font.rs
ndk/src/native_window.rs

- ndk/native_window: Add `set_buffers_transform()` API
- ndk/native_window: Add `try_allocate_buffers()` API
- ndk/native_window: Add `set_frame_rate*()` APIs since level 30/31
Note that this _lacks_ `ANativeWindow_readFromParcel`/`writeToParcel` which'll only appear in API level 34 with R26 which is still in beta.  Besides, we don't yet bind `AParcel` either.

ndk/native_window: Add missing function wrappers

---

ndk/CHANGELOG.md
ndk/src/bitmap.rs

This convention is already applied to `(Android)BitmapError` and `(Android)BitmapFormat`, and to many other `A`-prefixed structs elsewhere in the `ndk` crate: there is no need to repeat the Android prefix or letter when describing strucures and enumerations.
Also strip off the `Bitmap` prefix in a `Result` alias, which isn't common either when only filling in a default for the generic `Error` argument.

bitmap: Strip off repeated `Android` prefix from structs and enums

---

ndk/CHANGELOG.md
ndk/src/media/image_reader.rs
ndk/src/media_error.rs

~Depends on #431~
Since bumping our MSRV to 1.66 `num_enum` provides a `catch_all` variant which we can use to store yet-unknown or yet-unmapped error codes, rather than having them in a secondary `enum` which derives `thiserror`.
This also allows us to get rid of a manual `match` statement, which can be (but could already have been...) generated by `num_enum` via `TryFromPrimitive` before.

ndk/media_error: Flatten `MediaStatus` and `MediaError` with `catch_all`

---

ndk/CHANGELOG.md
ndk/Cargo.toml
ndk/src/native_window.rs

Following [the same strategy in winit], move `raw-window-handle 0.5` behind a `rwh_05` feature and add `raw-window-handle 0.4` and the newly released `raw-window-handle 0.6` behind a corresponding `rwh04`/`rwh_06` feature.  The new **non-raw** trait and **lifetimed** type since `0.6` have been implemented instead, as `raw-window-handle` provides blanket implementations to coerce/convert back to `Raw*` types.
[the same strategy in winit]: https://github.com/rust-windowing/winit/pull/3126

ndk/native_window: Implement `HasWindowHandle` for 0.4 and 0.6 (and maintain 0.5)

---

ndk/CHANGELOG.md
ndk/src/looper.rs

When `looper` calls a callback that triggered for a poll on a file descriptor it provides the reason for the wakeup, because users are allowed to register multiple.  Hence it is important for the user to know the trigger reason to enact on the result appropriately.  E.g. a `HANGUP` typically requires the callback to be deregistered by returning `false`, as the other end (for a `pipe()` or `socket()`) has been closed and this file descriptor should no longer trigger any other event.
Note that various events are received by this callback regardless of whether the user registered it with that flag in `events`. This is all reflected by updating the documentation comments for `FdEvent` based on upstream Android documentation.
Keep in mind that `FdEvent` is a `bitflag`, and Android uses that to …

looper: Provide `event` value to file descriptor poll callback

---

ndk/CHANGELOG.md
ndk/src/hardware_buffer.rs
ndk/src/native_window.rs

This was previously reexported from `hardware_buffer` in #276 to maintain backwards compatibility when the type was originally defined inside that module.  However, the type was also strangely reexported from `native_window` (probably a copy-paste error) while it is accessible from the public `hardware_buffer_format` module leading to **three** individual modules where `HardwareBufferFormat` can be imported from.
Reduce this duplication and confusion by forcing it to only be reachable from the canonical `hardware_buffer_format` module.

Remove public reexports of `HardwareBufferFormat`

---

ndk/src/bitmap.rs
ndk/src/data_space.rs
ndk/src/lib.rs
ndk/src/native_window.rs

The `DataSpace` type represents typical named color spaces, where each value is a bitmask comprising of a standard, transfer function, and range value.  All are implemented as `enum`s with `TryFromPrimitive` to make it obvious to see and handle unknown values, and include `#[non_exhaustive]` to allow us to bind new values in future non-breaking patch releases.

ndk: Add `DataSpace` type and fns on `Bitmap` and `NativeWindow`

---

ndk/CHANGELOG.md
ndk/src/bitmap.rs

Map the new compression functions that are available in API level 30, which also take a `DataSpace` that has recently been added in #438.
Also turn `BitmapError` into a proper `non_exhaustive` `enum` with `num_enum`'s `catch_all` parser, similar to `MediaError`.

bitmap: Add `compress()`/`compress_raw()` fns since API 30

---

ndk/CHANGELOG.md
ndk/Cargo.toml
ndk/src/lib.rs
ndk/src/shared_memory.rs

`ASharedMemory` allows allocating shared memory as a file descriptor that can be `mmap`ed or shared to other processes via parcels or Unix domain sockets.
Its Java counterpart is `android.os.SharedMemory` from which (when available as a JNI `jobject`) an owned file descriptor clone can be created to access the memory object in native code.
Common Rust traits such as `FromRawFd` are provided so that a `SharedMemory` object can also be created from a received file descriptor.

ndk: Add bindings for `ASharedMemory`

---

ndk/CHANGELOG.md
ndk/src/audio.rs
ndk/src/media_error.rs

Using the new `num_enum` `catch_all` we can now automatically implement the `match` statement and get rid of one superfluous `AudioError` variant.

audio: rename `AudioErrorResult` to `AudioResult` and make `non_exhaustive`

---

ndk-sys/CHANGELOG.md
ndk-sys/Cargo.toml
ndk-sys/src/lib.rs
ndk/CHANGELOG.md
ndk/Cargo.toml
ndk/src/lib.rs
ndk/src/sync.rs

Bind a few free functions and conveniently re-wrap the resulting struct types to access sync information from file descriptors, and merge sync file descriptors into one.

ndk: Add bindings for `sync.h`

---

.github/workflows/publish.yml
.github/workflows/rust.yml
ndk/Cargo.toml

One of our dependencies recently bumped its `rust-version` causing our MSRV test to _break again_.  It is undesired to randomly work around this by bumping our MSRV, or consistently have PRs/merges fail for unrelated reasons.
Instead, perform the MSRV-test with `-Zminimal-versions`.  This seems to be generally accepted in the Rust ecosystem (as there is otherwise no way for crates to bump MSRV barring a semver-breaking release) and prevents us from hitting unnecessary MSRV build failures caused by dependencies.
At the same time our minimal version bounds are now exercised, ensuring downstream crates depending on the `ndk` can build with `-Zminimal-versions` too - which required specifying a few patch bounds for our dependencies.
Unfortunately GitHub's UI for `continue-on-error: true` …

CI: Only require MSRV-check to succeed with `-Zminimal-versions`

---

ndk/CHANGELOG.md
ndk/src/media/media_codec.rs
ndk/src/media/media_format.rs
ndk/src/media/mod.rs

This type is used outside of `media_codec`, for example in the `media_extractor` bindings.

ndk/media: Move `MediaFormat` to its own module

---

ndk/Cargo.toml

The docs for this module are missing because its contents weren't picked up in the docs.rs build.

cargo: Add missing `sync` feature to `all`

---

README.md

The previous `> **Note**` syntax has been deprecated in favour of `> [!NOTE]` sytnax on November 14th (2 days ago), and newer block types were added: https://github.com/orgs/community/discussions/16925
I'm not quite sure if `IMPORTANT` carries the right load since `Crucial information necessary for users to succeed` is no longer really applicable; most users know where to find the crates and their names haven't changed on crates.io.
Finally, also mention `xbuild` being favoured over `cargo-apk` (even though there's _still_, after all these years some feature disparity).

README: Move modularization comment down and use new blockquote syntax

---

ndk/src/bitmap.rs

`clippy::missing_safety_doc` is turned on by default but didn't catch one `unsafe` function; that seems to have been fixed in Rust 1.74, for which we should add the missing reason why `compress_raw()` is annotated as `unsafe`.

ndk/bitmap: Add missing `# Safety` docs to satisfy Rust 1.74 lint

---

ndk/CHANGELOG.md
ndk/src/media/media_format.rs

CC @zarik5 @spencercw
Also provide the typical `try_clone()` method, and add missing doc aliases to all types and functions.

ndk/media_format: Implement `copy()`/`clear()` fns since API level 29

---

ndk/src/media/media_format.rs

CC @zarik5 @spencercw
Currently `Debug` only prints a raw pointer which is rather useless to look at.  In addition to the pointer, also print the `Display` representation of `MediaFormat` which uses Android's `toString()` function to create a human-readable string of the various fields set inside of it.
On a side-note it is "great" to see that `toString()` is not currently available as a user function via a lifetimed `CStr` as it is invalidated in a nontrivial way (e.g. when `toString()` is called again, and possibly also when `set_()` functions are called which are not currently borrowing it mutably).

ndk/media_format: Implement `Debug` in terms of `Display`

---

ndk/CHANGELOG.md
ndk/Cargo.toml
ndk/src/event.rs
ndk/src/input_queue.rs

These were added in API 31 (`KeyEvent`/`MotionEvent`) and API 33 (`InputEvent`), but not yet mapped in the NDK crate.

Add `from_java()` constructors to `InputQueue`, `KeyEvent` and `MotionEvent`

---

ndk/CHANGELOG.md
ndk/Cargo.toml
ndk/src/event.rs
ndk/src/looper.rs
ndk/src/native_activity.rs
ndk/src/native_window.rs

This `enum` was never `pub` even though it serves a slight purpose to more easily classify various event sources, which is accounted for in the bitmask-like value of `AINPUT_SOURCE_XXX`.

ndk/event: Implement `SourceClass` `bitflag` and provide `Source::class()` getter

---

ndk/CHANGELOG.md
ndk/src/bitmap.rs

Otherwise there is a compilation error when building with only the feature `bitmap`, due to the inexistence of the `DataSpace` type. `DataSpace` is defined with `api-level-28`, but this `BitmapCompressError` is only used by `Bitmap::compress()` and `Bitmap::compress_raw()`, which are only available with `api-level-30`.

ndk/bitmap: Gate `BitmapCompressError` behind `api-level-30`

---

ndk/src/event.rs
ndk/src/font.rs

These enums constantly get renumbered when the documentation, and might not point anywhere at all. `AFONT_WEIGHT_*` was pointing to `AFONT_VARIANT_`, and the `input`/`event` enums currently start at index 38.
CC @paxbun

ndk: Drop stale links to `anonymous-enum-xx` upstream docs

---

ndk/CHANGELOG.md
ndk/src/data_space.rs

This variant corresponds to `0`.  This missing variant was found while `Debug`-printing a `DataSpace` with the `__Unknown` PR, where `DataSpace::Unknown` printed `__Unknown(0)` for the range "field".

ndk/data_space: Add missing `DataSpaceRange::Unspecified` variant

---

ndk/CHANGELOG.md
ndk/src/media/media_format.rs

Fixes #451, CC @zarik5
All setters can inherently change the internals of the format, and should furthermore invalidate - or not be allowed while - borrowed strings or buffers (are) acquired from it.
Unforatunately [`getString()` is documented as]:
The returned string is owned by the format, and remains valid until the next call to getString, or until the format is deleted.
Meaning that it is not reentrant, and invalidates any data previously acquired from `str()`; hence this getter is marked as `&mut self` too. The same is however not the case for `getBuffer()`.
[`getString()` is documented as]: https://github.com/rust-mobile/ndk/issues/451

ndk/media_format: Make all mutating functions take `self` by `&mut`

---

ndk/CHANGELOG.md
ndk/src/audio.rs
ndk/src/media/image_reader.rs
ndk/src/media/media_codec.rs

Fixes #454
In all these cases the NDK either documents or implements the callback to be invoked from a single, separate thread.  For this to be allowed by Rust thread safety, the closures and their (moved) contents are effectively  "moved" to a different thread (`Send`) but not accessed concurrently (`Sync`), but the type definitions were never requiring this marker trait which could lead to undefined/invalid behaviour.
In addition some `Box`ed callbacks may have been dropped before a new callback is passed to the NDK, leading to a possible race condition. By storing the new callback _after_ registering it with the NDK, the previous callback is now dropped later to ensure such race conditions no longer happen (assuming AOSP callback invocations are properly synchronized with the setters). …

ndk: Requre all off-thread `dyn Fn*` callback types to implement `Send`

---

ndk/CHANGELOG.md
ndk/src/native_window.rs

This prefix is already included in the type name, when stripping down the "typename" `ANATIVEWINDOW_TRANSFORM_` prefix from every enum constant.

native_window: Remove redundant `TRANSFORM_` prefix from `NativeWindowTransform` variants

---

ndk/CHANGELOG.md
ndk/src/hardware_buffer.rs
ndk/src/media/image_reader.rs

`HardwareBufferUsage` really is a structure that comprises various usage flags, and was modeled as a hard-to-get `u64` value while being wrapped inside _two_ newtypes (one in the `ndk`, one in `ndk-sys`) and without the typical bit-ops (i.e. `BitOr`) one comes to expect.
This is all provided out of the box - and more helper functions - via `bitflags` with more convenient access to the raw value to beat.
Also inherit the upstream docs for convenience and completeness.

ndk/hardware_buffer: Convert `HardwareBufferUsage` to `bitflags`

---

ndk-sys/CHANGELOG.md
ndk-sys/Cargo.toml
ndk-sys/src/lib.rs
ndk/CHANGELOG.md
ndk/Cargo.toml
ndk/src/native_window.rs

Per [the `libandroid` function map][1] newer `NativeWindow` functions are no longer available; these instead need to be linked [from the `libnativewindow` library][2] directly.
[1]: https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/native/android/libandroid.map.txt;l=1?q=libandroid.map.txt&sq=&ss=android%2Fplatform%2Fsuperproject%2Fmain
[2]: https://cs.android.com/android/platform/superproject/main/+/main:frameworks/native/libs/nativewindow/libnativewindow.map.txt;l=1?q=libnativewindow.map.txt&sq=&ss=android%2Fplatform%2Fsuperproject%2Fmain
Ref: https://github.com/android/ndk/issues/1982

ndk/native_window: Link against `libnativewindow` for API >= 26 functions

---

ndk/CHANGELOG.md
ndk/src/audio.rs

Depends on #459
Now that `UnsupportedValue` is no longer part of `AudioError` thanks to all enums having a proper `__Unknown(x)` catch-all (making the `enum` API a whole lot more convenient to users), this `#[error]` enum is just a wrapper struct with only one variant.
Instead, drop `AudioError` and its `thiserror` wrapping completely, and import `Error` directly on the `aaudio_result_t` `enum` that is also renamed to `AudioError`.

ndk/audio: Merge `AudioResult` variant enum into `AudioError`

---

ndk/CHANGELOG.md
ndk/src/looper.rs

`ForeignLooper` allows (re)registering callbacks on threads that are not the `ThreadLooper` (current) thread.  Since these calls will be executed on that `ThreadLooper` thread when the user calls any of the `poll()` functions, these closures have to pass a thread boundary which requires `Send`.

looper: Require `Send` when adding fd event callbacks on `ForeignLooper`

---

ndk/CHANGELOG.md
ndk/src/media/image_reader.rs
ndk/src/media_error.rs

Both async and non-async `acquire_next/latest_image()` functions will return `ImgreaderNoBufferAvailable` when the producer has not provided a buffer that is either ready for consumption or that can be blocked on (either inside a non-async method, or by returning the accompanying fence file descriptor).  But only the non-`_async()` functions were marked as if this is a common case by returning an `Option<>`, seemingly out of the assumption that the `_async()` functions can _always_ give you an image (if the `MaxImagesAcquired` limit is not reached) but with a file-descriptor sync fence to wait on.  This is not the case as the producer needs to submit a buffer together with a sync fence on the producer-end first.
Hence the current API signatures create the false assumption that only …

ndk/image_reader: Special-case return statuses in `Image`-acquire functions

---

ndk-sys/src/lib.rs

[Rust nightly since May 6 2024] points out that `armv7` is not a known, valid value for the `target_arch` cfg variable.  This is confirmed by the docs not listing it either: https://doc.rust-lang.org/reference/conditional-compilation.html#target_arch
Hence drop this entirely, and rely purely on `target_arch = "arm"`.
[Rust nightly since May 6 2024]: https://blog.rust-lang.org/2024/05/06/check-cfg.html

ndk-sys: Drop cfg for inexistant `target_arch = "armv7"`

---

.github/workflows/rust.yml

A recent borked `cargo-ndk` release [^1] [^2] lead me to investigate why we are using a nonstandard tool in our CI in the first place. Compiling / build-testing the `ndk` crate does not require any external tooling whatsoever nor an SDK setup: this crate is a pure wrapper over pre-generated C bindings in the `ndk-sys` crate, which only require NDK _libraries_ (and an Android-capable linker) when linking actual runnable binaries (typically shared libraries or executables).  And the Rust compiler natively supports compiling Rust code for Android targets.
[^1]: https://github.com/rust-mobile/ndk/actions/runs/9149848316
[^2]: https://togithub.com/bbqsrc/cargo-ndk/pull/135#discussion_r1606097922

CI: Drop unneeded `cargo-ndk` tool from build-test

---

ndk/CHANGELOG.md
ndk/Cargo.toml
ndk/src/hardware_buffer.rs
ndk/src/media/image_reader.rs
ndk/src/surface_texture.rs

Android 14 (U, API level 34) adds `DataSpace` support to `ImageReader` with a new constructor and a getter, and finally switches to the regular `HardwareBufferFormat` instead of the restricted `ImageFormat` enum to select the underlying buffer format.  After all, an `AImage` can be turned into a `HardwareBuffer` which supports a wider range of formats.

image_reader: Add `AImageReader_newWithDataSpace()` from `api-level-34`

---

ndk-sys/Cargo.toml
ndk/Cargo.toml

`os::android-apis` is a new category that I added upstream in https://github.com/rust-lang/crates.io/pull/8558.  The rest already exists on crates.io, and should make it easier to find/place this crate.

cargo: Add `categories` for discoverability

---

ndk/CHANGELOG.md
ndk/Cargo.toml
ndk/src/lib.rs
ndk/src/performance_hint.rs

https://developer.android.com/ndk/reference/group/a-performance-hint
Performance Hint Manager allows apps to inform the system about workloads running on threads to more accurately allocate power for them. After the fact, applications should report back how long their operation actually ended up taking.
The new work duration API (driven by `AWorkDuration`) also includes GPU timings.

Add bindings for Performance Hint Manager

---

ndk/src/event.rs

CC @rib for https://github.com/rust-mobile/android-activity/pull/163

ndk/event: Add missing `Axis` variants and new `MotionClassification` API
